---
stages:
  - test
  - build
  - release

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.2.0
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

.prepareTox:
  script:
    - !reference [.load_github_key, script]
    - apt-get update && apt-get install -y gnupg
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main 13" | tee
      /etc/apt/sources.list.d/pgdg.list
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7FCC7D46ACCC4CF8
    - apt-get update
    - apt-get install -y postgresql-client-13
    - psql -U postgres -h postgres -c "create user test with superuser password 'test';"
    - psql -U postgres -h postgres -c "create database gdcdatamodel2 with owner test;"
    - pip install "tox<4"
  needs: [pre-commit]

tox:
  stage: test
  parallel:
    matrix:
      - PY_VER: ['3.6', '3.7', '3.8', '3.9']
  image: ${BASE_CONTAINER_REGISTRY}/python${PY_VER}-builder
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  tags:
    - dind
  variables:
    PG_HOST: postgres
    PG_PASS: test
    PG_USER: test
    PG_NAME: gdcdatamodel2
    PG_INDEXD_HOST: postgres
  before_script:
    - !reference [.prepareTox, script]
  needs:
    - !reference [.prepareTox, needs]
  script:
    - tox -r -e py


build_python_artifacts:
  image: docker.osdc.io/ncigdc/python3.6-builder
  stage: build
  script:
    - !reference [.load_github_key, script]
    - pwd
    - git fetch --unshallow    # have to fetch manually while GIT_STRATEGY is not working
    - cat setup.cfg
    - cat dev-requirements.txt
    - whoami
    - apt-get update
    - apt-get install -y python3-venv
    - pip3 install -U setuptools_scm build twine setuptools
    - python3 -m setuptools_scm
    - python3 -m build
    - ls -l dist
  variables:
    GIT_STRATEGY: clone   # need full clone for setuptools_scam
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week
  needs: [tox]

release_to_nexus:
  image: docker.osdc.io/ncigdc/python3.6-builder
  stage: release
  script:
    - ls -la dist
    - twine check dist/*
    - twine upload dist/*
  variables:
    TWINE_USERNAME: ${TWINE_USER}
    TWINE_PASSWORD: ${TWINE_PASSWORD}
    TWINE_REPOSITORY_URL: https://nexus.osdc.io/repository/pypi-snapshots/
  artifacts:
    paths:
      - dist/*.whl
    reports:
      dotenv: vars.env
  rules: # Override globally-defined RELEASE_REGISTRY
    - if: $CI_COMMIT_TAG
      when: always
      variables:
        TWINE_REPOSITORY_URL: https://nexus.osdc.io/repository/pypi-releases/
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
      variables:
        TWINE_REPOSITORY_URL: https://nexus.osdc.io/repository/pypi-releases/
    - if: $CI_COMMIT_REF_NAME =~ /master/
      when: always
      variables:
        TWINE_REPOSITORY_URL: https://nexus.osdc.io/repository/pypi-releases/
    - if: $CI_COMMIT_REF_NAME =~ /main/
      when: always
      variables:
        TWINE_REPOSITORY_URL: https://nexus.osdc.io/repository/pypi-releases/
    - when: always
  needs: [build_python_artifacts]
