---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-library.yaml

variables:
  LANGUAGE_VERSION: python3.9

tox:
  parallel:
    matrix:
      - LANGUAGE_VERSION:
          # TODO: add python3.13 after DEV-3751 merged into gdcdictionary & a new tag is
          # cut. Otherwise tests will fail for bug in the dictionary.
            [python3.9, python3.10, python3.11, python3.12]

  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
      variables:
        POSTGRES_PASS: test
        POSTGRES_HOST_AUTH_METHOD: trust
        PG_INIT_SQL: |
          create user test with superuser password 'test';
          create database gdcdatamodel2 with owner test;
  variables:
    PG_PASS: test
    PG_HOST: postgres
    PG_USER: postgres
    PG_NAME: gdcdatamodel2

publish:
  script:
    - echo "Publishing '$CI_COMMIT_TAG' to $TWINE_REPOSITORY with $TWINE_USERNAME"
    - pip install setuptools_scm versionista build twine
    - python -m setuptools_scm
    - python -m build
    - python -m twine check dist/*
    - python -m twine upload dist/* --repository-url $TWINE_REPOSITORY
