#!/usr/bin/env bash

VENV=venv_plaster
# needs python >= 3.8
virtualenv $VENV -p python3.8
source $VENV/bin/activate

python3 -m pip install \
    "plaster @ git+ssh://git@github.com/NCI-GDC/plaster.git@feat/dev-1932-add-module-docstring#egg=plaster" \
    "psqlgml>=0.2.4" \
    pre-commit
plaster --version
psqlgml --version
plaster generate -p gdcdictionary -o src/gdcdatamodel2/models -s src/gdcdatamodel2/partial_dictionary
pre-commit run -a

rm -rf $VENV
