title = "Data Model code generator configuration"

[environment]

[logging]
level = "INFO"
log_file = "plaster.log"

[profiles]

[profiles.gdcdictionary]
url = "https://github.com/NCI-GDC/gdcdictionary.git"
path = "gdcdictionary/schemas"
version = "2.3.1"
overwrite = false
type = "remote"
