#!/usr/bin/env bash

VENV=venv_plaster
# needs python >= 3.8
virtualenv $VENV -p python3.8
source $VENV/bin/activate

python3 -m pip install .[plaster]
plaster --version
psqlgml --version
plaster generate -p gdcdictionary -o src/gdcdatamodel2/models

rm -rf $VENV
