title = "Data Model code generator configuration"

[environment]

[logging]
level = "INFO"
log_file = "plaster.log"

[profiles]

[profiles.gdcdictionary]
url = "https://github.com/NCI-GDC/gdcdictionary.git"
path = "src/gdcdictionary/schemas"
version = "inoue-pathology_detail-DICT-345"
is_git_tag = false
overwrite = true
type = "remote"
