title = "Data Model code generator configuration"

[environment]

[logging]
level = "INFO"
log_file = "plaster.log"

[profiles]

[profiles.gdcdictionary]
url = "https://github.com/NCI-GDC/gdcdictionary.git"
path = "gdcdictionary/schemas"
version = "feat/dev-1672-automate-gdcdatamodel2-generation"
is_tag = false
overwrite = false
type = "remote"
