#!/usr/bin/env bash

VENV=venv_plaster
# needs python >= 3.8
virtualenv $VENV -p python3.8
source $VENV/bin/activate

python3 -m pip install "plaster @ git+ssh://git@github.com/NCI-GDC/plaster.git@1.0.4#egg=plaster" "psqlgml >= 0.2.0" pre-commit
plaster --version
psqlgml --version
plaster generate -p gdcdictionary -o src/gdcdatamodel2/models
pre-commit run -a

rm -rf $VENV
