[build-system]
requires = ["setuptools>=45", "wheel", "tomli>=1.0", "packaging>=20.0", "pyparsing>2,<3", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 98
include = '\.pyi?$'

[tool.coverage.html]
title = "gdcdatamodel2 coverage report"
directory = "docs/htmlcov"
show_contexts = true

[tool.coverage.run]
branch = true
context = "unit tests"
source = ["gdcdatamodel2"]

[tool.isort]
profile = "black"
line_length = 98              # match black config
known_first_party = ["gdcdatamodel2"]

[tool.setuptools_scm]
local_scheme = "no-local-version"

[tool.towncrier]
package = "gdcdatamodel2"
package_dir = "src"
filename = "changelog.rst"
directory = "changelog"
