[metadata]
name = gdcdatamodel2
description = Data models for gdcdictionary
long_description = file: README.md
long_description_content_type = text/markdown
author = Qiao Qiao
author_email = qiaoq@uchicago.edu
license = Apache Software License 2.0
license_file = LICENSE
url = https://github.com/NCI-GDC/gdcdatamodel2
keywords = python3 gdcdatamodels gdcdictionary plaster
classifiers =
    Programming Language :: PythonLicense :: OSI Approved :: Apache Software License
    Operating System :: Unix
    Operating System :: POSIX :: Linux
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Internet

[options]
zip_safe = True
packages = find:
package_dir =
    =src
python_requires = >=3.6
include_package_data = True
install_requires =
    psqlgraph @ git+https://github.com/NCI-GDC/psqlgraph.git@3.4.2#egg=psqlgraph


[options.packages.find]
where = src

[options.extras_require]
changelog =
    towncrier
dev =
    coverage[toml]
    gdcdictionary @ git+https://github.com/NCI-GDC/gdcdictionary.git@galileo-sample-DICT-306#egg=gdcdictionary
    pytest
    pytest-cov
    pytest-env
    typing_extensions; python_version < "3.8"
docs =
    sphinx
    sphinx_rtd_theme
    sphinxcontrib-napoleon
lint =
    mypy
    pre-commit
validators =
    gdcdictionary @ git+https://github.com/NCI-GDC/gdcdictionary.git@galileo-sample-DICT-306#egg=gdcdictionary
visualization =
    graphviz ~= 0.19.1
    ipython ~= 7.16.3
