[tox]
isolated_build = True

[testenv]
passenv:
    PG_*
setenv:
    NO_PROXY=localhost,postgres
    no_proxy=localhost,postgres
deps =
    .[dev, validators]
install_command =
    python -m pip install {opts} {packages}
commands =
    python -m pytest --cov=gdcdatamodel2 --cov-report html --cov-report term
[flake8]
ignore = E203, E266, E501, W503, F403, F401
max-line-length = 89
max-complexity = 18
exclude =
    .git
    .tox
    .pytest*
    htmlcov
    build
    dist
    *.pyc
    .eggs

[testenv:pre-commit]
skip_install = True
commands_pre =
deps =
    pre-commit

commands =
    pre-commit run --all-files --show-diff-on-failure {posargs: }

[testenv:docs]
commands =
    sphinx-build docs/source docs/build -b html

[testenv:plaster]
basepython = python3
extras =
    plaster
commands =
    plaster --version
    plaster generate -d gdcdictionary -o src/gdcdatamodel2/models

[testenv:publish]
passenv =
    TWINE_*
    CI_COMMIT_*
skip_install=true
deps =
    setuptools_scm
    setuptools-git-versioning
    build
    twine
install_command =
    python -m pip install {opts} {packages}
commands =
    python -m setuptools_git_versioning
    python -m build
    python -m twine check dist/*
    python -m twine upload dist/*
commands_post=
