[tox]
minversion = 4.5.0
isolated_build = True
skip_missing_interpreters = true

[testenv]
passenv:
    PG_*
setenv:
    NO_PROXY=localhost,postgres
    no_proxy=localhost,postgres
deps =
    .[dev, validators]
install_command =
    python -m pip install {opts} {packages}
commands =
    python -m pytest --cov=gdcdatamodel2 --cov-report html --cov-report term
[flake8]
ignore = E203, E266, E501, W503, F403, F401
max-line-length = 89
max-complexity = 18
exclude =
    .git
    .tox
    .pytest*
    htmlcov
    build
    dist
    *.pyc
    .eggs

[testenv:pre-commit]
skip_install = True
commands_pre =
deps =
    pre-commit

commands =
    pre-commit run --all-files --show-diff-on-failure {posargs: }

[testenv:docs]
commands =
    sphinx-build docs/source docs/build -b html

[testenv:plaster]
basepython = python3
extras =
    plaster
commands =
    plaster --version
    plaster generate -d gdcdictionary -o src/gdcdatamodel2/models

[testenv:publish]
allowlist_externals =
    echo
passenv =
    TWINE_*
    CI_COMMIT_*
skip_install=true
deps =
    build
    twine
    setuptools_scm
    versionista>=1.1.0
install_command =
    python -m pip install {opts} {packages}
commands =
    echo "Publishing '$CI_COMMIT_TAG' to $TWINE_REPOSITORY with $TWINE_USERNAME"
    python -m setuptools_scm
    python -m build
    python -m twine check dist/*
    python -m twine upload dist/* --repository-url $TWINE_REPOSITORY
commands_post=
