"""This module is for AlignedReadsIndexDerivedFromAlignedReads Edge.

This module is generated by plaster 1.1.2.dev6+fix.md5.hash.fix from gdcdictionary version 3.1.1.dev21,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AlignedReadsIndexDerivedFromAlignedReads(base.Edge):
    __tablename__: str = "edge_8f39509f_alreindefralre"

    __label__: str = "derived_from"
    __dst_class__: str = "AlignedReads"
    __dst_table__: str = "node_alignedreads"
    __src_class__: str = "AlignedReadsIndex"
    __src_table__: str = "node_alignedreadsindex"

    __dst_src_assoc__: str = "aligned_reads_indexes"
    __src_dst_assoc__: str = "aligned_reads_files"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
