"""This module is for AlignedReadsDataFromAlignmentCocleaningWorkflow Edge.

This module is generated by plaster 1.1.2.dev10+fix.md5.hash.fix from gdcdictionary version 3.1.1.dev2,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AlignedReadsDataFromAlignmentCocleaningWorkflow(base.Edge):
    __tablename__: str = "edge_7ae4f157_alredafralcowo"

    __label__: str = "data_from"
    __dst_class__: str = "AlignmentCocleaningWorkflow"
    __dst_table__: str = "node_alignmentcocleaningworkflow"
    __src_class__: str = "AlignedReads"
    __src_table__: str = "node_alignedreads"

    __dst_src_assoc__: str = "aligned_reads_files"
    __src_dst_assoc__: str = "alignment_cocleaning_workflows"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
