"""This module is for AnnotationAnnotatesAggregatedSomaticMutation Edge.

This module is generated by plaster 1.1.3 from gdcdictionary version 0.1.dev22,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AnnotationAnnotatesAggregatedSomaticMutation(base.Edge):
    __tablename__: str = "edge_8893f83c_ananagsomu"

    __label__: str = "annotates"
    __dst_class__: str = "AggregatedSomaticMutation"
    __dst_table__: str = "node_aggregatedsomaticmutation"
    __src_class__: str = "Annotation"
    __src_table__: str = "node_annotation"

    __dst_src_assoc__: str = "annotations"
    __src_dst_assoc__: str = "aggregated_somatic_mutations"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
