"""This module is for Annotation Node.

This module is generated by plaster 1.1.1 from gdcdictionary version 3.0.4.dev8,
please do not modify manually.
"""

from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import base, datetime_hooks, indexes, related_cases, versioned_nodes, versioning


class Annotation(base.Node):
    __tablename__: str = "node_annotation"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [["project_id", "submitter_id"]]

    # _defaults: default value for specified fields in the dictionary
    _defaults: Dict[str, Union[bool, float, int, str]] = {"state": "validated"}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {
        "title": "Annotation",
        "namespace": "https://gdc.cancer.gov",
        "category": "notation",
        "submittable": False,
        "downloadable": False,
        "description": "An explanatory or critical comment, or other in-context information (e.g., pattern, motif, link), that has been associated with data or other types of information. (NCIt C44272)",
        "required": ["submitter_id", "category"],
        "project": "*",
        "program": "*",
        "previous_version_downloadable": False,
    }

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "annotation"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def pg_secondary_keys(cls) -> List[List[str]]:
        return cls.__pg_secondary_keys

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {}

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
            "aggregated_somatic_mutations": {
                "backref": "annotations",
                "type": base.Node.get_subclass("aggregated_somatic_mutation"),
            },
            "aligned_reads_files": {
                "backref": "annotations",
                "type": base.Node.get_subclass("aligned_reads"),
            },
            "aligned_reads_indexes": {
                "backref": "annotations",
                "type": base.Node.get_subclass("aligned_reads_index"),
            },
            "aliquots": {
                "backref": "annotations",
                "type": base.Node.get_subclass("aliquot"),
            },
            "analysis_metadata_files": {
                "backref": "annotations",
                "type": base.Node.get_subclass("analysis_metadata"),
            },
            "analytes": {
                "backref": "annotations",
                "type": base.Node.get_subclass("analyte"),
            },
            "annotated_somatic_mutations": {
                "backref": "annotations",
                "type": base.Node.get_subclass("annotated_somatic_mutation"),
            },
            "archives": {
                "backref": "annotations",
                "type": base.Node.get_subclass("archive"),
            },
            "biospecimen_supplements": {
                "backref": "annotations",
                "type": base.Node.get_subclass("biospecimen_supplement"),
            },
            "cases": {
                "backref": "annotations",
                "type": base.Node.get_subclass("case"),
            },
            "centers": {
                "backref": "annotations",
                "type": base.Node.get_subclass("center"),
            },
            "clinical_supplements": {
                "backref": "annotations",
                "type": base.Node.get_subclass("clinical_supplement"),
            },
            "copy_number_auxiliary_files": {
                "backref": "annotations",
                "type": base.Node.get_subclass("copy_number_auxiliary_file"),
            },
            "copy_number_estimates": {
                "backref": "annotations",
                "type": base.Node.get_subclass("copy_number_estimate"),
            },
            "copy_number_segments": {
                "backref": "annotations",
                "type": base.Node.get_subclass("copy_number_segment"),
            },
            "demographics": {
                "backref": "annotations",
                "type": base.Node.get_subclass("demographic"),
            },
            "diagnoses": {
                "backref": "annotations",
                "type": base.Node.get_subclass("diagnosis"),
            },
            "experiment_metadata_files": {
                "backref": "annotations",
                "type": base.Node.get_subclass("experiment_metadata"),
            },
            "exposures": {
                "backref": "annotations",
                "type": base.Node.get_subclass("exposure"),
            },
            "family_histories": {
                "backref": "annotations",
                "type": base.Node.get_subclass("family_history"),
            },
            "files": {
                "backref": "annotations",
                "type": base.Node.get_subclass("file"),
            },
            "filtered_copy_number_segments": {
                "backref": "annotations",
                "type": base.Node.get_subclass("filtered_copy_number_segment"),
            },
            "follow_ups": {
                "backref": "annotations",
                "type": base.Node.get_subclass("follow_up"),
            },
            "gene_expressions": {
                "backref": "annotations",
                "type": base.Node.get_subclass("gene_expression"),
            },
            "masked_methylation_arrays": {
                "backref": "annotations",
                "type": base.Node.get_subclass("masked_methylation_array"),
            },
            "masked_somatic_mutations": {
                "backref": "annotations",
                "type": base.Node.get_subclass("masked_somatic_mutation"),
            },
            "methylation_beta_values": {
                "backref": "annotations",
                "type": base.Node.get_subclass("methylation_beta_value"),
            },
            "mirna_expressions": {
                "backref": "annotations",
                "type": base.Node.get_subclass("mirna_expression"),
            },
            "molecular_tests": {
                "backref": "annotations",
                "type": base.Node.get_subclass("molecular_test"),
            },
            "other_clinical_attributes": {
                "backref": "annotations",
                "type": base.Node.get_subclass("other_clinical_attribute"),
            },
            "pathology_details": {
                "backref": "annotations",
                "type": base.Node.get_subclass("pathology_detail"),
            },
            "pathology_reports": {
                "backref": "annotations",
                "type": base.Node.get_subclass("pathology_report"),
            },
            "portions": {
                "backref": "annotations",
                "type": base.Node.get_subclass("portion"),
            },
            "protein_expressions": {
                "backref": "annotations",
                "type": base.Node.get_subclass("protein_expression"),
            },
            "raw_methylation_arrays": {
                "backref": "annotations",
                "type": base.Node.get_subclass("raw_methylation_array"),
            },
            "read_group_qcs": {
                "backref": "annotations",
                "type": base.Node.get_subclass("read_group_qc"),
            },
            "read_groups": {
                "backref": "annotations",
                "type": base.Node.get_subclass("read_group"),
            },
            "run_metadata_files": {
                "backref": "annotations",
                "type": base.Node.get_subclass("run_metadata"),
            },
            "samples": {
                "backref": "annotations",
                "type": base.Node.get_subclass("sample"),
            },
            "secondary_expression_analyses": {
                "backref": "annotations",
                "type": base.Node.get_subclass("secondary_expression_analysis"),
            },
            "simple_germline_variations": {
                "backref": "annotations",
                "type": base.Node.get_subclass("simple_germline_variation"),
            },
            "simple_somatic_mutations": {
                "backref": "annotations",
                "type": base.Node.get_subclass("simple_somatic_mutation"),
            },
            "slide_images": {
                "backref": "annotations",
                "type": base.Node.get_subclass("slide_image"),
            },
            "slides": {
                "backref": "annotations",
                "type": base.Node.get_subclass("slide"),
            },
            "somatic_mutation_indexes": {
                "backref": "annotations",
                "type": base.Node.get_subclass("somatic_mutation_index"),
            },
            "structural_variations": {
                "backref": "annotations",
                "type": base.Node.get_subclass("structural_variation"),
            },
            "submitted_aligned_reads_files": {
                "backref": "annotations",
                "type": base.Node.get_subclass("submitted_aligned_reads"),
            },
            "submitted_genomic_profiles": {
                "backref": "annotations",
                "type": base.Node.get_subclass("submitted_genomic_profile"),
            },
            "submitted_genotyping_arrays": {
                "backref": "annotations",
                "type": base.Node.get_subclass("submitted_genotyping_array"),
            },
            "submitted_methylation_beta_values": {
                "backref": "annotations",
                "type": base.Node.get_subclass("submitted_methylation_beta_value"),
            },
            "submitted_tangent_copy_numbers": {
                "backref": "annotations",
                "type": base.Node.get_subclass("submitted_tangent_copy_number"),
            },
            "submitted_unaligned_reads_files": {
                "backref": "annotations",
                "type": base.Node.get_subclass("submitted_unaligned_reads"),
            },
            "tissue_source_sites": {
                "backref": "annotations",
                "type": base.Node.get_subclass("tissue_source_site"),
            },
            "treatments": {
                "backref": "annotations",
                "type": base.Node.get_subclass("treatment"),
            },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
            "aggregated_somatic_mutations": {
                "edge_out": "_AnnotationAnnotatesAggregatedSomaticMutation_out",
                "dst_type": base.Node.get_subclass("aggregated_somatic_mutation"),
            },
            "aligned_reads_files": {
                "edge_out": "_AnnotationAnnotatesAlignedReads_out",
                "dst_type": base.Node.get_subclass("aligned_reads"),
            },
            "aligned_reads_indexes": {
                "edge_out": "_AnnotationAnnotatesAlignedReadsIndex_out",
                "dst_type": base.Node.get_subclass("aligned_reads_index"),
            },
            "aliquots": {
                "edge_out": "_AnnotationAnnotatesAliquot_out",
                "dst_type": base.Node.get_subclass("aliquot"),
            },
            "analysis_metadata_files": {
                "edge_out": "_AnnotationAnnotatesAnalysisMetadata_out",
                "dst_type": base.Node.get_subclass("analysis_metadata"),
            },
            "analytes": {
                "edge_out": "_AnnotationAnnotatesAnalyte_out",
                "dst_type": base.Node.get_subclass("analyte"),
            },
            "annotated_somatic_mutations": {
                "edge_out": "_AnnotationAnnotatesAnnotatedSomaticMutation_out",
                "dst_type": base.Node.get_subclass("annotated_somatic_mutation"),
            },
            "archives": {
                "edge_out": "_AnnotationAnnotatesArchive_out",
                "dst_type": base.Node.get_subclass("archive"),
            },
            "biospecimen_supplements": {
                "edge_out": "_AnnotationAnnotatesBiospecimenSupplement_out",
                "dst_type": base.Node.get_subclass("biospecimen_supplement"),
            },
            "cases": {
                "edge_out": "_AnnotationAnnotatesCase_out",
                "dst_type": base.Node.get_subclass("case"),
            },
            "centers": {
                "edge_out": "_AnnotationAnnotatesCenter_out",
                "dst_type": base.Node.get_subclass("center"),
            },
            "clinical_supplements": {
                "edge_out": "_AnnotationAnnotatesClinicalSupplement_out",
                "dst_type": base.Node.get_subclass("clinical_supplement"),
            },
            "copy_number_auxiliary_files": {
                "edge_out": "_AnnotationAnnotatesCopyNumberAuxiliaryFile_out",
                "dst_type": base.Node.get_subclass("copy_number_auxiliary_file"),
            },
            "copy_number_estimates": {
                "edge_out": "_AnnotationAnnotatesCopyNumberEstimate_out",
                "dst_type": base.Node.get_subclass("copy_number_estimate"),
            },
            "copy_number_segments": {
                "edge_out": "_AnnotationAnnotatesCopyNumberSegment_out",
                "dst_type": base.Node.get_subclass("copy_number_segment"),
            },
            "demographics": {
                "edge_out": "_AnnotationAnnotatesDemographic_out",
                "dst_type": base.Node.get_subclass("demographic"),
            },
            "diagnoses": {
                "edge_out": "_AnnotationAnnotatesDiagnosis_out",
                "dst_type": base.Node.get_subclass("diagnosis"),
            },
            "experiment_metadata_files": {
                "edge_out": "_AnnotationAnnotatesExperimentMetadata_out",
                "dst_type": base.Node.get_subclass("experiment_metadata"),
            },
            "exposures": {
                "edge_out": "_AnnotationAnnotatesExposure_out",
                "dst_type": base.Node.get_subclass("exposure"),
            },
            "family_histories": {
                "edge_out": "_AnnotationAnnotatesFamilyHistory_out",
                "dst_type": base.Node.get_subclass("family_history"),
            },
            "files": {
                "edge_out": "_AnnotationAnnotatesFile_out",
                "dst_type": base.Node.get_subclass("file"),
            },
            "filtered_copy_number_segments": {
                "edge_out": "_AnnotationAnnotatesFilteredCopyNumberSegment_out",
                "dst_type": base.Node.get_subclass("filtered_copy_number_segment"),
            },
            "follow_ups": {
                "edge_out": "_AnnotationAnnotatesFollowUp_out",
                "dst_type": base.Node.get_subclass("follow_up"),
            },
            "gene_expressions": {
                "edge_out": "_AnnotationAnnotatesGeneExpression_out",
                "dst_type": base.Node.get_subclass("gene_expression"),
            },
            "masked_methylation_arrays": {
                "edge_out": "_AnnotationAnnotatesMaskedMethylationArray_out",
                "dst_type": base.Node.get_subclass("masked_methylation_array"),
            },
            "masked_somatic_mutations": {
                "edge_out": "_AnnotationAnnotatesMaskedSomaticMutation_out",
                "dst_type": base.Node.get_subclass("masked_somatic_mutation"),
            },
            "methylation_beta_values": {
                "edge_out": "_AnnotationAnnotatesMethylationBetaValue_out",
                "dst_type": base.Node.get_subclass("methylation_beta_value"),
            },
            "mirna_expressions": {
                "edge_out": "_AnnotationAnnotatesMirnaExpression_out",
                "dst_type": base.Node.get_subclass("mirna_expression"),
            },
            "molecular_tests": {
                "edge_out": "_AnnotationAnnotatesMolecularTest_out",
                "dst_type": base.Node.get_subclass("molecular_test"),
            },
            "other_clinical_attributes": {
                "edge_out": "_AnnotationAnnotatesOtherClinicalAttribute_out",
                "dst_type": base.Node.get_subclass("other_clinical_attribute"),
            },
            "pathology_details": {
                "edge_out": "_AnnotationAnnotatesPathologyDetail_out",
                "dst_type": base.Node.get_subclass("pathology_detail"),
            },
            "pathology_reports": {
                "edge_out": "_AnnotationAnnotatesPathologyReport_out",
                "dst_type": base.Node.get_subclass("pathology_report"),
            },
            "portions": {
                "edge_out": "_AnnotationAnnotatesPortion_out",
                "dst_type": base.Node.get_subclass("portion"),
            },
            "protein_expressions": {
                "edge_out": "_AnnotationAnnotatesProteinExpression_out",
                "dst_type": base.Node.get_subclass("protein_expression"),
            },
            "raw_methylation_arrays": {
                "edge_out": "_AnnotationAnnotatesRawMethylationArray_out",
                "dst_type": base.Node.get_subclass("raw_methylation_array"),
            },
            "read_group_qcs": {
                "edge_out": "_AnnotationAnnotatesReadGroupQc_out",
                "dst_type": base.Node.get_subclass("read_group_qc"),
            },
            "read_groups": {
                "edge_out": "_AnnotationAnnotatesReadGroup_out",
                "dst_type": base.Node.get_subclass("read_group"),
            },
            "run_metadata_files": {
                "edge_out": "_AnnotationAnnotatesRunMetadata_out",
                "dst_type": base.Node.get_subclass("run_metadata"),
            },
            "samples": {
                "edge_out": "_AnnotationAnnotatesSample_out",
                "dst_type": base.Node.get_subclass("sample"),
            },
            "secondary_expression_analyses": {
                "edge_out": "_AnnotationAnnotatesSecondaryExpressionAnalysis_out",
                "dst_type": base.Node.get_subclass("secondary_expression_analysis"),
            },
            "simple_germline_variations": {
                "edge_out": "_AnnotationAnnotatesSimpleGermlineVariation_out",
                "dst_type": base.Node.get_subclass("simple_germline_variation"),
            },
            "simple_somatic_mutations": {
                "edge_out": "_AnnotationAnnotatesSimpleSomaticMutation_out",
                "dst_type": base.Node.get_subclass("simple_somatic_mutation"),
            },
            "slide_images": {
                "edge_out": "_AnnotationAnnotatesSlideImage_out",
                "dst_type": base.Node.get_subclass("slide_image"),
            },
            "slides": {
                "edge_out": "_AnnotationAnnotatesSlide_out",
                "dst_type": base.Node.get_subclass("slide"),
            },
            "somatic_mutation_indexes": {
                "edge_out": "_AnnotationAnnotatesSomaticMutationIndex_out",
                "dst_type": base.Node.get_subclass("somatic_mutation_index"),
            },
            "structural_variations": {
                "edge_out": "_AnnotationAnnotatesStructuralVariation_out",
                "dst_type": base.Node.get_subclass("structural_variation"),
            },
            "submitted_aligned_reads_files": {
                "edge_out": "_AnnotationAnnotatesSubmittedAlignedReads_out",
                "dst_type": base.Node.get_subclass("submitted_aligned_reads"),
            },
            "submitted_genomic_profiles": {
                "edge_out": "_AnnotationAnnotatesSubmittedGenomicProfile_out",
                "dst_type": base.Node.get_subclass("submitted_genomic_profile"),
            },
            "submitted_genotyping_arrays": {
                "edge_out": "_AnnotationAnnotatesSubmittedGenotypingArray_out",
                "dst_type": base.Node.get_subclass("submitted_genotyping_array"),
            },
            "submitted_methylation_beta_values": {
                "edge_out": "_AnnotationAnnotatesSubmittedMethylationBetaValue_out",
                "dst_type": base.Node.get_subclass("submitted_methylation_beta_value"),
            },
            "submitted_tangent_copy_numbers": {
                "edge_out": "_AnnotationAnnotatesSubmittedTangentCopyNumber_out",
                "dst_type": base.Node.get_subclass("submitted_tangent_copy_number"),
            },
            "submitted_unaligned_reads_files": {
                "edge_out": "_AnnotationAnnotatesSubmittedUnalignedReads_out",
                "dst_type": base.Node.get_subclass("submitted_unaligned_reads"),
            },
            "tissue_source_sites": {
                "edge_out": "_AnnotationAnnotatesTissueSourceSite_out",
                "dst_type": base.Node.get_subclass("tissue_source_site"),
            },
            "treatments": {
                "edge_out": "_AnnotationAnnotatesTreatment_out",
                "dst_type": base.Node.get_subclass("treatment"),
            },
        }

    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False

    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(f"{self} not bound to a session. Try .get_versions(session).")
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )

    @psqlgraph.pg_property(str)
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum=[
            "error",
            "invalid",
            "live",
            "md5summed",
            "md5summing",
            "redacted",
            "released",
            "submitted",
            "suppressed",
            "uploaded",
            "uploading",
            "validated",
            "validating",
        ],
    )
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, type(None))
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, type(None))
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum=[
            "Acceptable treatment for TCGA tumor",
            "Administrative Compliance",
            "Alternate sample pipeline",
            "BCR Notification",
            "Barcode incorrect",
            "Biospecimen identity unknown",
            "Case submitted is found to be a recurrence after submission",
            "Center QC failed",
            "Clinical data insufficient",
            "Duplicate case",
            "Duplicate item",
            "General",
            "Genotype mismatch",
            "History of acceptable prior treatment related to a prior/other malignancy",
            "History of unacceptable prior treatment related to a prior/other malignancy",
            "Inadvertently shipped",
            "Item Flagged Low Quality",
            "Item does not meet study protocol",
            "Item flagged DNU",
            "Item in special subset",
            "Item is noncanonical",
            "Item may not meet study protocol",
            "Molecular analysis outside specification",
            "Neoadjuvant therapy",
            "New notification type",
            "New observation type",
            "Normal class but appears diseased",
            "Normal tissue origin incorrect",
            "Observation",
            "Pathology outside specification",
            "Permanently missing item or object",
            "Prior malignancy",
            "Qualification metrics changed",
            "Qualified in error",
            "Sample compromised",
            "Subject identity unknown",
            "Subject withdrew consent",
            "Synchronous malignancy",
            "Tumor class but appears normal",
            "Tumor tissue origin incorrect",
            "Tumor type incorrect",
            "WGA Failure",
        ],
    )
    def category(self, value):
        self._set_property("category", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum=[
            "Blocking Release",
            "CenterNotification",
            "Complete Data Freeze",
            "Downstream Data Freeze",
            "Notification",
            "Observation",
            "Redaction",
        ],
    )
    def classification(self, value):
        self._set_property("classification", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def creator(self, value):
        self._set_property("creator", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def notes(self, value):
        self._set_property("notes", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum=["Approved", "Rescinded"])
    def status(self, value):
        self._set_property("status", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, type(None))
    def legacy_created_datetime(self, value):
        self._set_property("legacy_created_datetime", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, type(None))
    def legacy_updated_datetime(self, value):
        self._set_property("legacy_updated_datetime", value)  # type: ignore  # inherited from CommonBase


datetime_hooks.cls_inject_created_datetime_hook(Annotation)
datetime_hooks.cls_inject_updated_datetime_hook(Annotation)
