"""This module is for AnnotationAnnotatesMaskedMethylationArray Edge.

This module is generated by plaster 1.1.3.dev4+feat.dev.2807.add.nosec from gdcdictionary version 3.2.2,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AnnotationAnnotatesMaskedMethylationArray(base.Edge):
    __tablename__: str = "edge_c22497b4_ananmamear"

    __label__: str = "annotates"
    __dst_class__: str = "MaskedMethylationArray"
    __dst_table__: str = "node_maskedmethylationarray"
    __src_class__: str = "Annotation"
    __src_table__: str = "node_annotation"

    __dst_src_assoc__: str = "annotations"
    __src_dst_assoc__: str = "masked_methylation_arrays"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
