"""This module is for AnnotatedSomaticMutationDataFromSomaticAnnotationWorkflow Edge.

This module is generated by plaster 1.1.1.dev3+feat.dev.2483.update.md5.function.for.amazon.linux from gdcdictionary version 3.0.3.dev1,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AnnotatedSomaticMutationDataFromSomaticAnnotationWorkflow(base.Edge):
    __tablename__: str = "edge_023eaa75_ansomudafrsoanwo"

    __label__: str = "data_from"
    __dst_class__: str = "SomaticAnnotationWorkflow"
    __dst_table__: str = "node_somaticannotationworkflow"
    __src_class__: str = "AnnotatedSomaticMutation"
    __src_table__: str = "node_annotatedsomaticmutation"

    __dst_src_assoc__: str = "annotated_somatic_mutations"
    __src_dst_assoc__: str = "somatic_annotation_workflows"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
