"""This module is for AnnotationAnnotatesSimpleSomaticMutation Edge.

This module is generated by plaster 1.1.2 from gdcdictionary version 3.1.1.dev4,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AnnotationAnnotatesSimpleSomaticMutation(base.Edge):
    __tablename__: str = "edge_bd252a4a_anansisomu"

    __label__: str = "annotates"
    __dst_class__: str = "SimpleSomaticMutation"
    __dst_table__: str = "node_simplesomaticmutation"
    __src_class__: str = "Annotation"
    __src_table__: str = "node_annotation"

    __dst_src_assoc__: str = "annotations"
    __src_dst_assoc__: str = "simple_somatic_mutations"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
