"""This module is for AnnotationAnnotatesSubmittedUnalignedReads Edge.

This module is generated by plaster 1.1.3 from gdcdictionary version 3.3.1.dev8,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AnnotationAnnotatesSubmittedUnalignedReads(base.Edge):
    __tablename__: str = "edge_d0856409_anansuunre"

    __label__: str = "annotates"
    __dst_class__: str = "SubmittedUnalignedReads"
    __dst_table__: str = "node_submittedunalignedreads"
    __src_class__: str = "Annotation"
    __src_table__: str = "node_annotation"

    __dst_src_assoc__: str = "annotations"
    __src_dst_assoc__: str = "submitted_unaligned_reads_files"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
