"""This module is for AnnotationAnnotatesRunMetadata Edge.

This module is generated by plaster 1.0.10.dev14+faet.dev.2444.use.without.profile from gdcdictionary version feat/dev-2459-update-gitlab-ci,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class AnnotationAnnotatesRunMetadata(base.Edge):
    __tablename__: str = "edge_annotationannotatesrunmetadata"

    __label__: str = "annotates"
    __dst_class__: str = "RunMetadata"
    __dst_table__: str = "node_runmetadata"
    __src_class__: str = "Annotation"
    __src_table__: str = "node_annotation"

    __dst_src_assoc__: str = "annotations"
    __src_dst_assoc__: str = "run_metadata_files"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass