"""This module is for BiospecimenSupplementDerivedFromCase Edge.

This module is generated by plaster 1.0.10.dev5+faet.dev.2444.use.without.profile from gdcdictionary version feat/dev-2459-update-gitlab-ci,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class BiospecimenSupplementDerivedFromCase(base.Edge):
    __tablename__: str = "edge_a15bc39a_bisudefrca"

    __label__: str = "derived_from"
    __dst_class__: str = "Case"
    __dst_table__: str = "node_case"
    __src_class__: str = "BiospecimenSupplement"
    __src_table__: str = "node_biospecimensupplement"

    __dst_src_assoc__: str = "biospecimen_supplements"
    __src_dst_assoc__: str = "cases"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass