"""This module is for BiospecimenSupplementMemberOfArchive Edge.

This module is generated by plaster 1.1.1 from gdcdictionary version 3.0.4.dev63,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class BiospecimenSupplementMemberOfArchive(base.Edge):
    __tablename__: str = "edge_c1329437_bisumeofar"

    __label__: str = "member_of"
    __dst_class__: str = "Archive"
    __dst_table__: str = "node_archive"
    __src_class__: str = "BiospecimenSupplement"
    __src_table__: str = "node_biospecimensupplement"

    __dst_src_assoc__: str = "biospecimen_supplements"
    __src_dst_assoc__: str = "archives"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
