"""This module is for CopyNumberSegmentDerivedFromGenomicProfileHarmonizationWorkflow Edge.

This module is generated by plaster 1.1.1 from gdcdictionary version 3.0.4.dev45,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class CopyNumberSegmentDerivedFromGenomicProfileHarmonizationWorkflow(base.Edge):
    __tablename__: str = "edge_724a3a7c_conusedefrgeprhawo"

    __label__: str = "derived_from"
    __dst_class__: str = "GenomicProfileHarmonizationWorkflow"
    __dst_table__: str = "node_genomicprofileharmonizationworkflow"
    __src_class__: str = "CopyNumberSegment"
    __src_table__: str = "node_copynumbersegment"

    __dst_src_assoc__: str = "copy_number_segments"
    __src_dst_assoc__: str = "genomic_profile_harmonization_workflows"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
