"""This module is for DataReleaseDescribesRoot Edge.

This module is generated by plaster 1.1.3 from gdcdictionary version 3.4.5.dev18,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class DataReleaseDescribesRoot(base.Edge):
    __tablename__: str = "edge_datareleasedescribesroot"

    __label__: str = "describes"
    __dst_class__: str = "Root"
    __dst_table__: str = "node_root"
    __src_class__: str = "DataRelease"
    __src_table__: str = "node_datarelease"

    __dst_src_assoc__: str = "data_releases"
    __src_dst_assoc__: str = "roots"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
