"""This module is for FileDataFromPortion Edge.

This module is generated by plaster 1.1.4.dev10+head from gdcdictionary version 3.4.5.dev1,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class FileDataFromPortion(base.Edge):
    __tablename__: str = "edge_filedatafromportion"

    __label__: str = "data_from"
    __dst_class__: str = "Portion"
    __dst_table__: str = "node_portion"
    __src_class__: str = "File"
    __src_table__: str = "node_file"

    __dst_src_assoc__: str = "files"
    __src_dst_assoc__: str = "portions"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
