"""This module is for FileSubmittedByCenter Edge.

This module is generated by plaster 1.1.3 from gdcdictionary version 3.4.5.dev1,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class FileSubmittedByCenter(base.Edge):
    __tablename__: str = "edge_filesubmittedbycenter"

    __label__: str = "submitted_by"
    __dst_class__: str = "Center"
    __dst_table__: str = "node_center"
    __src_class__: str = "File"
    __src_table__: str = "node_file"

    __dst_src_assoc__: str = "files"
    __src_dst_assoc__: str = "centers"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
