"""This module is for FileMemberOfExperimentalStrategy Edge.

This module is generated by plaster 1.1.2.dev6+fix.md5.hash.fix from gdcdictionary version 3.1.1.dev21,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class FileMemberOfExperimentalStrategy(base.Edge):
    __tablename__: str = "edge_filememberofexperimentalstrategy"

    __label__: str = "member_of"
    __dst_class__: str = "ExperimentalStrategy"
    __dst_table__: str = "node_experimentalstrategy"
    __src_class__: str = "File"
    __src_table__: str = "node_file"

    __dst_src_assoc__: str = "files"
    __src_dst_assoc__: str = "experimental_strategies"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
