"""This module is for FileMemberOfDataFormat Edge.

This module is generated by plaster 1.1.2a2 from gdcdictionary version 3.1.1.dev2,
please do not modify manually.
"""

from typing import Callable, List

import psqlgraph

from .helpers import base, related_cases


class FileMemberOfDataFormat(base.Edge):
    __tablename__: str = "edge_filememberofdataformat"

    __label__: str = "member_of"
    __dst_class__: str = "DataFormat"
    __dst_table__: str = "node_dataformat"
    __src_class__: str = "File"
    __src_table__: str = "node_file"

    __dst_src_assoc__: str = "files"
    __src_dst_assoc__: str = "data_formats"

    _session_hooks_before_insert: List[Callable] = psqlgraph.Edge._session_hooks_before_insert + [
        related_cases.cache_related_cases_on_insert
    ]

    _session_hooks_before_update: List[Callable] = psqlgraph.Edge._session_hooks_before_update + [
        related_cases.cache_related_cases_on_update
    ]

    _session_hooks_before_delete: List[Callable] = psqlgraph.Edge._session_hooks_before_delete + [
        related_cases.cache_related_cases_on_delete
    ]

    @classmethod
    def post_process(cls) -> None:
        pass
