from typing import Any, Dict, List, Tuple, Union, Optional

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import query, Session

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioning,
    versioned_nodes,
)


class MolecularTest(base.Node):
    __tablename__: str = "node_moleculartest"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [["project_id", "submitter_id"]]

    # _defaults: default value for specified fields in the dictionary
    _defaults: Dict[str, Union[bool, float, int, str]] = {"state": "validated"}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {
        "title": "Molecular Test",
        "namespace": "https://gdc.cancer.gov",
        "category": "clinical",
        "submittable": True,
        "downloadable": False,
        "description": "Information pertaining to any molecular tests performed on the patient during a clinical event.",
        "required": [
            "submitter_id",
            "gene_symbol",
            "molecular_analysis_method",
            "test_result",
        ],
        "project": "*",
        "program": "*",
        "previous_version_downloadable": False,
    }

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "molecular_test"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
            "annotations": {
                "name": "molecular_tests",
                "src_type": base.Node.get_subclass("annotation"),
            },
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
            "annotations": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("annotation"),
            },
            "diagnoses": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("diagnosis"),
            },
            "follow_ups": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("follow_up"),
            },
            "slides": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("slide"),
            },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
            "diagnoses": {
                "edge_out": "_MolecularTestRelatedToDiagnosis_out",
                "dst_type": base.Node.get_subclass("diagnosis"),
            },
            "follow_ups": {
                "edge_out": "_MolecularTestPerformedAtFollowUp_out",
                "dst_type": base.Node.get_subclass("follow_up"),
            },
            "slides": {
                "edge_out": "_MolecularTestRelatedToSlide_out",
                "dst_type": base.Node.get_subclass("slide"),
            },
        }

    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False

    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(
                "{} not bound to a session. Try .get_versions(session).".format(self)
            )
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )

    @psqlgraph.pg_property(str)
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "validated",
            "error",
            "md5summing",
            "released",
            "invalid",
            "live",
            "submitted",
            "md5summed",
            "uploading",
            "validating",
            "redacted",
            "uploaded",
            "suppressed",
        },
    )
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(type(None), str)
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(type(None), str)
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def aa_change(self, value):
        self._set_property("aa_change", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "CD30",
            "CD34",
            "Squamous Cell Carcinoma Antigen (SCCA)",
            "CD5",
            "CD14",
            "CD79A",
            "Ki67",
            "CD10",
            "CD22",
            "CD138",
            "Not Reported",
            "CD45",
            "CD23",
            "CD15",
            "Kappa, Surface",
            "CD33",
            "CA-125",
            "FMC-7",
            "CD56",
            "BCL6",
            "CD7",
            "Unknown",
            "NSE",
            "CEA",
            "CD3",
            "CA19-9",
            "CD20",
            "CD19",
            "CD25",
            "CCND1",
            "HLA-DR",
            "Mesothelin",
            "Prostate-Specific Antigen (PSA)",
            "Immunoglobulin, Surface",
            "TAG-72",
            "Lambda, Surface",
            "Immunoglobulin, Cytoplasmic",
            "CD117",
        },
    )
    def antigen(self, value):
        self._set_property("antigen", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Monosomy", "Trisomy"})
    def aneuploidy(self, value):
        self._set_property("aneuploidy", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Involved Tissue, NOS",
            "Plasma",
            "Unknown",
            "Connective Tissue",
            "Uninvolved Tissue, NOS",
            "Tissue, NOS",
            "Skin",
            "Feces",
            "Cerebrospinal Fluid",
            "Nerve Tissue",
            "Not Reported",
            "Granulocyte",
            "Muscle Tissue",
            "Bone Marrow",
            "Blood",
            "Serum",
            "Buffy Coat",
            "Peritoneal Fluid",
            "Saliva",
            "Embryonic Tissue",
            "Pleural Fluid",
            "Urine",
            "Soft Tissue",
            "Buccal Mucosa",
            "Embryonic Fluid",
        },
    )
    def biospecimen_type(self, value):
        self._set_property("biospecimen_type", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def biospecimen_volume(self, value):
        self._set_property("biospecimen_volume", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def blood_test_normal_range_lower(self, value):
        self._set_property("blood_test_normal_range_lower", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def blood_test_normal_range_upper(self, value):
        self._set_property("blood_test_normal_range_upper", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def cell_count(self, value):
        self._set_property("cell_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "chr12",
            "chr1",
            "chr14",
            "chr22",
            "chr5",
            "chr16",
            "chr9",
            "chr11",
            "Not Reported",
            "chr20",
            "chr10",
            "chr18",
            "chr19",
            "chr4",
            "chr21",
            "chr2",
            "chrY",
            "chrX",
            "chr8",
            "chr6",
            "chr17",
            "chr7",
            "chr3",
            "chr15",
            "chrM",
            "chr23",
            "chr13",
        },
    )
    def chromosome(self, value):
        self._set_property("chromosome", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def copy_number(self, value):
        self._set_property("copy_number", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Clonal", "Non-clonal"})
    def clonality(self, value):
        self._set_property("clonality", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "t(8;21)",
            "t(3;5)(q25;q34)",
            "t(6;11)(q27;q23)",
            "t(10;11)(p11.2;q23)",
            "t(6;9)",
            "Not Reported",
            "t(9;11)(p22;q23)",
            "t(11;19)(q23;p13.1)",
        },
    )
    def chromosomal_translocation(self, value):
        self._set_property("chromosomal_translocation", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"p", "q", "Not Reported"})
    def chromosome_arm(self, value):
        self._set_property("chromosome_arm", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def cytoband(self, value):
        self._set_property("cytoband", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def days_to_test(self, value):
        self._set_property("days_to_test", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def exon(self, value):
        self._set_property("exon", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "HOXB1",
            "FCRL4",
            "CARD11",
            "POLD1",
            "EZR",
            "HOXD11",
            "TRAF7",
            "POU5F1",
            "NBN",
            "PTPN11",
            "CCR4",
            "PTCH1",
            "TNFRSF14",
            "ABL1",
            "CHIC2",
            "RNF213",
            "CDH10",
            "NUP214",
            "TOP1",
            "SEPT9",
            "COL2A1",
            "ESR1",
            "GAS7",
            "DAXX",
            "LRIG3",
            "XPC",
            "FOXR1",
            "ZFHX3",
            "CANT1",
            "TRA",
            "FOXP1",
            "TGFBR2",
            "EML4",
            "SMAD3",
            "RAF1",
            "SSX1",
            "ETV1",
            "DGCR8",
            "TPM4",
            "RET",
            "NBEA",
            "DDB2",
            "WAS",
            "BCL11A",
            "FGFR2",
            "MLLT4",
            "CDK6",
            "NSD1",
            "DDIT3",
            "PPP2R1A",
            "NFE2L2",
            "CDK4",
            "AMER1",
            "CNTRL",
            "CIITA",
            "RPL10",
            "NACA",
            "TMEM127",
            "BRD3",
            "NUTM2A",
            "NONO",
            "MAP2K2",
            "BCL9",
            "DNM2",
            "RGPD3",
            "MAML2",
            "MLH1",
            "FANCA",
            "MAX",
            "ELK4",
            "HSP90AA1",
            "MAP2K1",
            "STRN",
            "MYCN",
            "PRPF40B",
            "EZH2",
            "TSC1",
            "PWWP2A",
            "COL1A1",
            "STAT5B",
            "SRC",
            "STAG1",
            "PBX1",
            "FAM47C",
            "ETNK1",
            "PLAG1",
            "PTK6",
            "SMO",
            "PMS2",
            "ZNRF3",
            "MLH2",
            "ERCC2",
            "CSMD3",
            "CD209",
            "EIF3E",
            "CALB2",
            "AXIN2",
            "SET",
            "ANK1",
            "PLCG1",
            "ZNF429",
            "BCOR",
            "FANCE",
            "TNC",
            "CHCHD7",
            "KNSTRN",
            "MAP3K13",
            "USP8",
            "CBLB",
            "XPO1",
            "AR",
            "Not Applicable",
            "ZNF331",
            "PTPRC",
            "CREBBP",
            "MB21D2",
            "Unknown",
            "WIF1",
            "FAT1",
            "MSI2",
            "ATM",
            "CLP1",
            "OMD",
            "SH3GL1",
            "EGFR",
            "SMARCD1",
            "EWSR1",
            "REL",
            "ALK",
            "COX6C",
            "MN1",
            "CDX2",
            "AKAP9",
            "CLTCL1",
            "CUL3",
            "FH",
            "KMT2D",
            "SKI",
            "MYH9",
            "ETV5",
            "FGFR1OP",
            "TPM3",
            "KLF4",
            "LARP4B",
            "PIK3CB",
            "KAT6B",
            "NUMA1",
            "ZNF444",
            "CAMTA1",
            "RABEP1",
            "STIL",
            "DCTN1",
            "ERCC5",
            "POLG",
            "MLF1",
            "CYP2C8",
            "MAF",
            "BTG1",
            "PRKCB",
            "KDR",
            "SPECC1",
            "SUFU",
            "MYC",
            "EPCAM",
            "DEK",
            "ACSL3",
            "ERBB4",
            "PTPRK",
            "TLX1",
            "CREB3L2",
            "MPL",
            "IGKC",
            "TNFRSF17",
            "SDHD",
            "USP6",
            "LIFR",
            "NTRK1",
            "TBX3",
            "CD28",
            "SETBP1",
            "SFPQ",
            "RUNX1T1",
            "FLCN",
            "SMARCA4",
            "PTPN6",
            "LPP",
            "BAP1",
            "EIF4A2",
            "BCL10",
            "TFPT",
            "ECT2L",
            "MALAT1",
            "PREX2",
            "PMS1",
            "SDC4",
            "CDKN1B",
            "P2RY8",
            "PAX8",
            "LMO1",
            "FANCC",
            "KDM6A",
            "S100A7",
            "EP300",
            "SMAD2",
            "LSM14A",
            "JAK3",
            "SOX2",
            "ATRX",
            "FSTL3",
            "ERCC4",
            "PHOX2B",
            "YWHAE",
            "FOXL2",
            "PER1",
            "CCNC",
            "FLI1",
            "PRKAR1A",
            "CNBP",
            "ZNF479",
            "TEC",
            "TAL2",
            "MAP2K4",
            "BRIP1",
            "GNAQ",
            "SBDS",
            "FEN1",
            "TBL1XR1",
            "PDE4DIP",
            "SETD2",
            "KRAS",
            "CDK12",
            "HIST1H4I",
            "CTCF",
            "JAZF1",
            "BCORL1",
            "MTOR",
            "PRCC",
            "HEY1",
            "HNF1A",
            "HOXA13",
            "Not Reported",
            "PAX5",
            "FIP1L1",
            "MYO5A",
            "ACVR2A",
            "FGFR4",
            "B2M",
            "CBFA2T3",
            "EPHA7",
            "CUX1",
            "KCNJ5",
            "HLA-A",
            "KDM5A",
            "CCNB1IP1",
            "KDSR",
            "KIT",
            "PPARG",
            "FOXA1",
            "PTEN",
            "EPAS1",
            "SRGAP3",
            "NOTCH2",
            "CARS",
            "DDX5",
            "FAM131B",
            "EIF1AX",
            "CRNKL1",
            "BCL3",
            "CCR7",
            "AFF1",
            "CDKN2A",
            "TRD",
            "HIST1H3B",
            "SH2B3",
            "GPHN",
            "IRF4",
            "RANBP2",
            "CHEK2",
            "SNX29",
            "RAD21",
            "BTK",
            "CD79A",
            "IGH",
            "NAB2",
            "EBF1",
            "NFKB2",
            "MLLT11",
            "ZRSR2",
            "AFF3",
            "WRN",
            "ATF1",
            "NFATC2",
            "PTPN13",
            "CYSLTR2",
            "RAC1",
            "BCL6",
            "CTNND2",
            "EXT1",
            "ASXL2",
            "MYCL",
            "MGMT",
            "FUS",
            "IL6ST",
            "HLF",
            "BRAF",
            "CDKN2C",
            "LHFP",
            "SYK",
            "SIRPA",
            "ZNF521",
            "RNF43",
            "DROSHA",
            "TNFAIP3",
            "H3F3B",
            "MLLT10",
            "NIN",
            "SEPT6",
            "POLQ",
            "STAG2",
            "CBLC",
            "MAPK1",
            "RUNX1",
            "CNOT3",
            "TCF3",
            "AXIN1",
            "KIF5B",
            "PPFIBP1",
            "FHIT",
            "BRCA2",
            "IKBKB",
            "GRM3",
            "FAT4",
            "FAS",
            "FGFR1",
            "CSF3R",
            "PPM1D",
            "AKT1",
            "ZEB1",
            "ZNF198",
            "KLK2",
            "ERBB2",
            "POU2AF1",
            "CRLF2",
            "CALR",
            "RAD51B",
            "CD99",
            "MECOM",
            "TRIP11",
            "CRTC3",
            "SMARCE1",
            "WT1",
            "RHOA",
            "GLI1",
            "SND1",
            "GCET1",
            "PRKACA",
            "NRG1",
            "TP53",
            "WDCP",
            "TRB",
            "MEN1",
            "NFKBIE",
            "PRRX1",
            "CDH17",
            "TET2",
            "TP63",
            "ACSL6",
            "GOPC",
            "NFIB",
            "SGK1",
            "HMGN2P46",
            "ROS1",
            "SDHA",
            "RPL5",
            "SLC45A3",
            "CLIP1",
            "ERC1",
            "RMI2",
            "ASPSCR1",
            "BLM",
            "FLT4",
            "NR4A3",
            "MSH2",
            "ERBB3",
            "KMT2C",
            "RSPO2",
            "TSHR",
            "KLF6",
            "FBXW7",
            "SRSF2",
            "ABI1",
            "THRAP3",
            "NCKIPSD",
            "CD274",
            "MSN",
            "GATA2",
            "PDPN",
            "DDX10",
            "AFF4",
            "FBLN2",
            "LMNA",
            "BCL2L12",
            "POT1",
            "KTN1",
            "MAFB",
            "ARID2",
            "ABL2",
            "NCOR2",
            "ELN",
            "TRIM27",
            "JAK2",
            "SMARCB1",
            "A1CF",
            "FANCF",
            "SHTN1",
            "CACNA1D",
            "KNL1",
            "NDRG1",
            "CIC",
            "TRIM33",
            "WWTR1",
            "HOXC13",
            "DCAF12L2",
            "PRDM1",
            "SPEN",
            "RECQL4",
            "PAX3",
            "CHGA",
            "TFE3",
            "TRIM24",
            "ARHGEF12",
            "ARHGAP26",
            "LEF1",
            "DNAJB1",
            "ID3",
            "CBL",
            "HIF1A",
            "SUZ12",
            "EED",
            "PML",
            "SEPT5",
            "JAK1",
            "NSD2",
            "IDH1",
            "IL21R",
            "RBM10",
            "TFG",
            "NUP98",
            "RSPO3",
            "FNBP1",
            "MDM2",
            "PTGS2",
            "MDM4",
            "MDS2",
            "LCP1",
            "MUC16",
            "NF1",
            "RB1",
            "VTI1A",
            "CCND2",
            "CNBD1",
            "BARD1",
            "CLTC",
            "NTRK3",
            "BRCA1",
            "PIK3CA",
            "SALL4",
            "FGFR3",
            "PSIP1",
            "SRSF3",
            "TFRC",
            "STAT6",
            "CYLD",
            "ARID1A",
            "SYP",
            "PGR",
            "DNTT",
            "BCR",
            "CEBPA",
            "CRTC1",
            "GRIN2A",
            "NRAS",
            "ATP1A1",
            "EXT2",
            "HOXC11",
            "HRAS",
            "CCND1",
            "CREB1",
            "ALDH2",
            "DICER1",
            "KAT6A",
            "MUC1",
            "IL7R",
            "CBFB",
            "IGL",
            "CCND3",
            "KRT7",
            "FCGR2B",
            "PRF1",
            "DDR2",
            "PDGFB",
            "PIM1",
            "HOXA11",
            "VHL",
            "BCL2",
            "DUX4L1",
            "FANCG",
            "LZTR1",
            "GATA3",
            "MIB1",
            "TLR2",
            "SF3B1",
            "APOBEC3B",
            "RAP1GDS1",
            "TRRAP",
            "TSC2",
            "CHST11",
            "MYB",
            "ZCCHC8",
            "MKL1",
            "IRS4",
            "SMC1A",
            "HSP90AB1",
            "TCL1A",
            "APC",
            "FBXO11",
            "ROBO2",
            "NCOA2",
            "NSD3",
            "BRD4",
            "DNMT3A",
            "SFRP4",
            "NF2",
            "CCNE1",
            "FANCD2",
            "MSH6",
            "ATR",
            "FLNA",
            "CTNNA2",
            "OLIG2",
            "RGS7",
            "TET1",
            "ACVR1",
            "HOXA9",
            "SDHB",
            "TCF12",
            "FAM135B",
            "NPM1",
            "ELF4",
            "COL3A1",
            "AKT3",
            "SS18",
            "POLE",
            "HIP1",
            "PDGFRA",
            "RALGDS",
            "FES",
            "AKT2",
            "ARAF",
            "ACKR3",
            "CDKN1A",
            "TLX3",
            "BUB1B",
            "MALT1",
            "CXCR4",
            "CASP8",
            "GNAS",
            "MLLT3",
            "FEV",
            "SMAD4",
            "CHD4",
            "FLT3",
            "NKX2-1",
            "FKBP9",
            "NT5C2",
            "ZBTB16",
            "ITK",
            "PHF6",
            "FAM46C",
            "FUBP1",
            "H3F3A",
            "LASP1",
            "PTPRT",
            "IGK",
            "PATZ1",
            "BIRC6",
            "RARA",
            "KIAA1549",
            "VAV1",
            "BCL7A",
            "TFEB",
            "XPA",
            "KMT2A",
            "NCOA1",
            "ZNF384",
            "QKI",
            "PABPC1",
            "TAF15",
            "FOXO3",
            "BMP5",
            "SSX2",
            "LRP1B",
            "RBM15",
            "HOXD13",
            "AQP1",
            "MNX1",
            "SDHAF2",
            "TMPRSS2",
            "ELL",
            "EPHA3",
            "PRDM16",
            "IL2",
            "PDCD1LG2",
            "JUN",
            "SPOP",
            "BCLAF1",
            "IKZF1",
            "MUTYH",
            "KAT7",
            "ATP2B3",
            "LYL1",
            "HMGA2",
            "PALB2",
            "HERPUD1",
            "FOXO4",
            "PPP6C",
            "ARID1B",
            "NTHL1",
            "GPC3",
            "PIK3R1",
            "LCK",
            "RPN1",
            "SS18L1",
            "HNRNPA2B1",
            "CEP89",
            "ETV6",
            "FOXO1",
            "PICALM",
            "TCEA1",
            "STK11",
            "HMGA1",
            "KRT20",
            "IDH2",
            "MYOD1",
            "KEAP1",
            "SDHC",
            "GNA11",
            "TAL1",
            "PTPRB",
            "CNTNAP2",
            "HOOK3",
            "PCM1",
            "MLLT1",
            "ISX",
            "GMPS",
            "SSX4",
            "ETV4",
            "ZMYM3",
            "PDGFRB",
            "TCF7L2",
            "SLC34A2",
            "CREB3L1",
            "CHD2",
            "UBR5",
            "BCL11B",
            "MYD88",
            "CSF1R",
            "NUTM2B",
            "CDH1",
            "MAP3K1",
            "TERT",
            "PBRM1",
            "MET",
            "NUTM1",
            "CCDC6",
            "GOLGA5",
            "PAX7",
            "PRDM2",
            "MYH11",
            "MAML3",
            "EPS15",
            "FAT3",
            "GATA1",
            "PCBP1",
            "NOTCH1",
            "MTCP1",
            "DDX6",
            "MED12",
            "MITF",
            "ARNT",
            "PAFAH1B2",
            "ATIC",
            "ELF3",
            "RHOH",
            "RPL22",
            "ERCC3",
            "CD79B",
            "ITGAV",
            "KDM5C",
            "BCL9L",
            "DDX3X",
            "LMO2",
            "NCOR1",
            "MUC4",
            "TPR",
            "SOCS1",
            "BIRC3",
            "MLLT6",
            "CDC73",
            "CTNNB1",
            "DCC",
            "CD74",
            "CTNND1",
            "NCOA4",
            "STAT3",
            "CDH11",
            "ARHGAP5",
            "ASXL1",
            "C15orf65",
            "WNK2",
            "U2AF1",
            "BMPR1A",
            "ERG",
        },
    )
    def gene_symbol(self, value):
        self._set_property("gene_symbol", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str, enum={"H4", "Unknown", "H1", "H3", "Not Reported", "H2B", "H2A"}
    )
    def histone_family(self, value):
        self._set_property("histone_family", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "H2A.Z.2.2",
            "H2A.X",
            "mH2A",
            "H2A.Z",
            "H2A.Z.2",
            "H3.X",
            "mH2A.2",
            "H3.5",
            "Not Reported",
            "H3.3",
            "H2A-Bbd",
            "H3.2",
            "CENP-A",
            "H3t (H3.4)",
            "mH2A.1",
            "H2A.Z.1",
            "H3.1",
            "H3.Y",
        },
    )
    def histone_variant(self, value):
        self._set_property("histone_variant", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "HPV45",
            "HPV39",
            "HPV16",
            "HPV58",
            "HPV33",
            "HPV66",
            "HPV56",
            "HPV18",
            "HPV35",
            "HPV52",
            "HPV31",
            "HPV51",
            "HPV73",
            "HPV68",
            "HPV59",
        },
    )
    def hpv_strain(self, value):
        self._set_property("hpv_strain", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def intron(self, value):
        self._set_property("intron", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Immunoglobulin A",
            "Basophil",
            "Beta 2 Microglobulin",
            "Serum Free Immunoglobulin Light Chain, Kappa",
            "Chromogranin A",
            "Blood Urea Nitrogen",
            "Lymphocytes",
            "M Protein",
            "Hematocrit",
            "Dopamine-Secreting",
            "Myeloblasts",
            "Eosinophil",
            "Immunoglobulin M",
            "Human Papillomavirus",
            "Absolute Neutrophil",
            "Blast Count",
            "Glucose",
            "Epstein-Barr Virus",
            "Unknown",
            "HPV-E6/E7",
            "Lymphoblasts",
            "Total Bilirubin",
            "Cytokeratin 5",
            "BG8",
            "Norepinephrine-Secreting",
            "Hemoglobin",
            "Promonocytes",
            "Leukocytes",
            "Lactate Dehydrogenase",
            "Platelets",
            "Metamyelocytes",
            "C-Reactive Protein",
            "Immunoglobulin G",
            "Alpha Fetoprotein",
            "Metanephrine-Secreting",
            "TAG-72",
            "B-cell genotyping",
            "Epinephrine-Secreting",
            "5-Hydroxyindoleacetic Acid",
            "Normetanephrine-Secreting",
            "Serum Mesothelin",
            "Neutrophil Bands",
            "Not Reported",
            "Metaphase Nucleus Count",
            "Cytokeratin 6",
            "Methoxytyramine-Secreting",
            "Myelocytes",
            "Prothrombin Time",
            "Total Protein",
            "Serum Free Immunoglobulin Light Chain, Lambda",
            "Albumin",
            "Calcium",
            "Human Chorionic Gonadotropin",
            "Promyelocytes",
            "Microsatellite Instability",
            "Testosterone",
            "Circulating Tumor Cells",
            "Minimal Residual Disease",
            "Creatinine",
            "Monocytes",
            "Erythrocyte Sedimentation Rate",
            "Cellularity",
            "Chromogranin B",
            "Serum Free Immunoglobulin Light Chain, NOS",
            "Prolymphocytes",
            "Circulating Endothelial Cells",
            "Luteinizing Hormone",
            "Gamma-Enolase",
            "Segmented Neutrophil",
        },
    )
    def laboratory_test(self, value):
        self._set_property("laboratory_test", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def loci_abnormal_count(self, value):
        self._set_property("loci_abnormal_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def loci_count(self, value):
        self._set_property("loci_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def locus(self, value):
        self._set_property("locus", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Unknown", "No", "Not Reported", "Yes"})
    def mismatch_repair_mutation(self, value):
        self._set_property("mismatch_repair_mutation", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def mitotic_count(self, value):
        self._set_property("mitotic_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def mitotic_total_area(self, value):
        self._set_property("mitotic_total_area", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "Microarray",
            "Karyotype",
            "Nuclear Staining",
            "ISH",
            "Southern Blotting",
            "Flow Cytometry",
            "Not Reported",
            "Targeted Sequencing",
            "PCR",
            "WXS",
            "Immunofluorescence",
            "WGS",
            "IHC",
            "Comparative Genomic Hybridization",
            "Sequencing, NOS",
            "FISH",
            "RT-PCR",
            "Cytogenetics, NOS",
            "Microsatellite Analysis",
            "RNA Sequencing",
            "Other",
        },
    )
    def molecular_analysis_method(self, value):
        self._set_property("molecular_analysis_method", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Incomplete Terminal Codon Variant",
            "Splice Donor Variant",
            "Missense Variant",
            "Nonsense",
            "Start Lost",
            "Inframe Deletion",
            "Splice Acceptor Variant",
            "Stop Retained Variant",
            "Synonymous Variant",
            "5 Prime UTR Variant",
            "Exon Variant",
            "TFBS Amplification",
            "Inframe Insertion",
            "Splice Region Variant",
            "3 Prime UTR Variant",
            "Transcript Ablation",
            "Non-coding Transcript Exon Variant",
            "Mature miRNA Variant",
            "Regulatory Region Amplification",
            "Intergenic Variant",
            "Frameshift Variant",
            "Transcript Amplification",
            "Feature Truncation",
            "Coding Sequence Variant",
            "Stop Lost",
            "Downstream Gene Variant",
            "Upstream Gene Variant",
            "Intron Variant",
            "Feature Elongation",
            "TFBS Ablation",
            "Protein Altering Variant",
            "Regulatory Region Ablation",
            "Stop Gain",
            "Non-coding Transcript Variant",
            "TF Binding Site Variant",
            "NMD Transcript Variant",
            "Regulatory Region Variant",
        },
    )
    def molecular_consequence(self, value):
        self._set_property("molecular_consequence", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"61", "13", "12"})
    def mutation_codon(self, value):
        self._set_property("mutation_codon", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Likely Benign",
            "Likely Pathogenic",
            "Pathogenic",
            "Benign",
            "Uncertain Significance",
        },
    )
    def pathogenicity(self, value):
        self._set_property("pathogenicity", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Aneuploid",
            "Unknown",
            "Not Reported",
            "Hyperdiploid",
            "Diploid",
            "Tetraploid",
            "Hypodiploid",
            "Near Diploid",
        },
    )
    def ploidy(self, value):
        self._set_property("ploidy", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def second_exon(self, value):
        self._set_property("second_exon", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "HOXB1",
            "FCRL4",
            "CARD11",
            "POLD1",
            "EZR",
            "HOXD11",
            "TRAF7",
            "POU5F1",
            "NBN",
            "PTPN11",
            "CCR4",
            "PTCH1",
            "TNFRSF14",
            "ABL1",
            "CHIC2",
            "RNF213",
            "CDH10",
            "NUP214",
            "TOP1",
            "SEPT9",
            "COL2A1",
            "ESR1",
            "GAS7",
            "DAXX",
            "LRIG3",
            "XPC",
            "FOXR1",
            "ZFHX3",
            "CANT1",
            "TRA",
            "FOXP1",
            "TGFBR2",
            "EML4",
            "SMAD3",
            "RAF1",
            "SSX1",
            "ETV1",
            "DGCR8",
            "TPM4",
            "RET",
            "NBEA",
            "DDB2",
            "WAS",
            "BCL11A",
            "FGFR2",
            "MLLT4",
            "CDK6",
            "NSD1",
            "DDIT3",
            "PPP2R1A",
            "NFE2L2",
            "CDK4",
            "AMER1",
            "CNTRL",
            "CIITA",
            "RPL10",
            "NACA",
            "TMEM127",
            "BRD3",
            "NUTM2A",
            "NONO",
            "MAP2K2",
            "BCL9",
            "DNM2",
            "RGPD3",
            "MAML2",
            "MLH1",
            "FANCA",
            "MAX",
            "ELK4",
            "HSP90AA1",
            "MAP2K1",
            "STRN",
            "MYCN",
            "PRPF40B",
            "EZH2",
            "TSC1",
            "PWWP2A",
            "COL1A1",
            "STAT5B",
            "SRC",
            "STAG1",
            "PBX1",
            "FAM47C",
            "ETNK1",
            "PLAG1",
            "PTK6",
            "SMO",
            "PMS2",
            "ZNRF3",
            "MLH2",
            "ERCC2",
            "CSMD3",
            "CD209",
            "EIF3E",
            "AXIN2",
            "SET",
            "ANK1",
            "PLCG1",
            "ZNF429",
            "BCOR",
            "FANCE",
            "TNC",
            "CHCHD7",
            "KNSTRN",
            "MAP3K13",
            "USP8",
            "CBLB",
            "XPO1",
            "AR",
            "ZNF331",
            "PTPRC",
            "CREBBP",
            "MB21D2",
            "Unknown",
            "WIF1",
            "FAT1",
            "MSI2",
            "ATM",
            "CLP1",
            "OMD",
            "SH3GL1",
            "EGFR",
            "SMARCD1",
            "EWSR1",
            "REL",
            "ALK",
            "COX6C",
            "MN1",
            "CDX2",
            "AKAP9",
            "CLTCL1",
            "CUL3",
            "FH",
            "KMT2D",
            "SKI",
            "MYH9",
            "ETV5",
            "FGFR1OP",
            "TPM3",
            "KLF4",
            "LARP4B",
            "PIK3CB",
            "KAT6B",
            "NUMA1",
            "ZNF444",
            "CAMTA1",
            "RABEP1",
            "STIL",
            "DCTN1",
            "ERCC5",
            "POLG",
            "MLF1",
            "CYP2C8",
            "MAF",
            "BTG1",
            "PRKCB",
            "KDR",
            "SPECC1",
            "SUFU",
            "MYC",
            "DEK",
            "ACSL3",
            "ERBB4",
            "PTPRK",
            "TLX1",
            "CREB3L2",
            "MPL",
            "TNFRSF17",
            "USP6",
            "SDHD",
            "LIFR",
            "NTRK1",
            "TBX3",
            "CD28",
            "SETBP1",
            "SFPQ",
            "RUNX1T1",
            "FLCN",
            "SMARCA4",
            "PTPN6",
            "LPP",
            "BAP1",
            "EIF4A2",
            "BCL10",
            "TFPT",
            "ECT2L",
            "MALAT1",
            "PREX2",
            "PMS1",
            "SDC4",
            "CDKN1B",
            "P2RY8",
            "PAX8",
            "LMO1",
            "FANCC",
            "KDM6A",
            "S100A7",
            "EP300",
            "SMAD2",
            "LSM14A",
            "JAK3",
            "SOX2",
            "ATRX",
            "FSTL3",
            "ERCC4",
            "PHOX2B",
            "YWHAE",
            "FOXL2",
            "PER1",
            "CCNC",
            "FLI1",
            "PRKAR1A",
            "CNBP",
            "ZNF479",
            "TEC",
            "TAL2",
            "MAP2K4",
            "BRIP1",
            "GNAQ",
            "SBDS",
            "FEN1",
            "TBL1XR1",
            "PDE4DIP",
            "SETD2",
            "KRAS",
            "CDK12",
            "HIST1H4I",
            "CTCF",
            "JAZF1",
            "BCORL1",
            "MTOR",
            "PRCC",
            "HEY1",
            "HNF1A",
            "HOXA13",
            "Not Reported",
            "PAX5",
            "FIP1L1",
            "MYO5A",
            "ACVR2A",
            "FGFR4",
            "B2M",
            "CBFA2T3",
            "EPHA7",
            "CUX1",
            "KCNJ5",
            "HLA-A",
            "KDM5A",
            "CCNB1IP1",
            "KDSR",
            "KIT",
            "PPARG",
            "FOXA1",
            "PTEN",
            "EPAS1",
            "SRGAP3",
            "NOTCH2",
            "CARS",
            "DDX5",
            "FAM131B",
            "EIF1AX",
            "CRNKL1",
            "BCL3",
            "CCR7",
            "AFF1",
            "CDKN2A",
            "TRD",
            "HIST1H3B",
            "SH2B3",
            "GPHN",
            "IRF4",
            "RANBP2",
            "CHEK2",
            "SNX29",
            "RAD21",
            "BTK",
            "CD79A",
            "IGH",
            "NAB2",
            "EBF1",
            "NFKB2",
            "MLLT11",
            "ZRSR2",
            "AFF3",
            "WRN",
            "ATF1",
            "NFATC2",
            "PTPN13",
            "CYSLTR2",
            "RAC1",
            "BCL6",
            "CTNND2",
            "EXT1",
            "ASXL2",
            "MYCL",
            "MGMT",
            "FUS",
            "IL6ST",
            "HLF",
            "BRAF",
            "CDKN2C",
            "LHFP",
            "SYK",
            "SIRPA",
            "ZNF521",
            "RNF43",
            "DROSHA",
            "TNFAIP3",
            "H3F3B",
            "MLLT10",
            "NIN",
            "SEPT6",
            "POLQ",
            "STAG2",
            "CBLC",
            "MAPK1",
            "RUNX1",
            "CNOT3",
            "TCF3",
            "AXIN1",
            "KIF5B",
            "PPFIBP1",
            "FHIT",
            "BRCA2",
            "IKBKB",
            "GRM3",
            "FAT4",
            "FAS",
            "FGFR1",
            "CSF3R",
            "PPM1D",
            "AKT1",
            "ZEB1",
            "ZNF198",
            "KLK2",
            "ERBB2",
            "POU2AF1",
            "CRLF2",
            "CALR",
            "RAD51B",
            "CD99",
            "MECOM",
            "TRIP11",
            "CRTC3",
            "SMARCE1",
            "WT1",
            "RHOA",
            "GLI1",
            "SND1",
            "PRKACA",
            "NRG1",
            "TP53",
            "WDCP",
            "TRB",
            "MEN1",
            "NFKBIE",
            "PRRX1",
            "CDH17",
            "TET2",
            "TP63",
            "ACSL6",
            "GOPC",
            "NFIB",
            "SGK1",
            "HMGN2P46",
            "ROS1",
            "SDHA",
            "RPL5",
            "SLC45A3",
            "CLIP1",
            "ERC1",
            "RMI2",
            "ASPSCR1",
            "BLM",
            "FLT4",
            "NR4A3",
            "MSH2",
            "ERBB3",
            "KMT2C",
            "RSPO2",
            "TSHR",
            "KLF6",
            "FBXW7",
            "SRSF2",
            "ABI1",
            "THRAP3",
            "NCKIPSD",
            "CD274",
            "MSN",
            "GATA2",
            "DDX10",
            "AFF4",
            "FBLN2",
            "LMNA",
            "BCL2L12",
            "POT1",
            "KTN1",
            "MAFB",
            "ARID2",
            "ABL2",
            "NCOR2",
            "ELN",
            "TRIM27",
            "JAK2",
            "SMARCB1",
            "A1CF",
            "FANCF",
            "SHTN1",
            "CACNA1D",
            "KNL1",
            "NDRG1",
            "CIC",
            "TRIM33",
            "WWTR1",
            "HOXC13",
            "DCAF12L2",
            "PRDM1",
            "SPEN",
            "RECQL4",
            "PAX3",
            "CHGA",
            "TFE3",
            "TRIM24",
            "ARHGEF12",
            "ARHGAP26",
            "LEF1",
            "DNAJB1",
            "ID3",
            "CBL",
            "HIF1A",
            "SUZ12",
            "EED",
            "PML",
            "SEPT5",
            "JAK1",
            "NSD2",
            "IDH1",
            "IL21R",
            "RBM10",
            "TFG",
            "NUP98",
            "RSPO3",
            "FNBP1",
            "MDM2",
            "MDM4",
            "MDS2",
            "LCP1",
            "MUC16",
            "NF1",
            "RB1",
            "VTI1A",
            "CCND2",
            "CNBD1",
            "BARD1",
            "CLTC",
            "NTRK3",
            "BRCA1",
            "PIK3CA",
            "SALL4",
            "FGFR3",
            "PSIP1",
            "SRSF3",
            "TFRC",
            "STAT6",
            "CYLD",
            "ARID1A",
            "SYP",
            "PGR",
            "BCR",
            "CEBPA",
            "CRTC1",
            "GRIN2A",
            "NRAS",
            "ATP1A1",
            "EXT2",
            "HOXC11",
            "HRAS",
            "CCND1",
            "CREB1",
            "ALDH2",
            "DICER1",
            "KAT6A",
            "MUC1",
            "IL7R",
            "CBFB",
            "IGL",
            "CCND3",
            "FCGR2B",
            "PRF1",
            "DDR2",
            "PDGFB",
            "PIM1",
            "HOXA11",
            "VHL",
            "BCL2",
            "DUX4L1",
            "FANCG",
            "LZTR1",
            "GATA3",
            "TLR2",
            "SF3B1",
            "APOBEC3B",
            "RAP1GDS1",
            "TRRAP",
            "TSC2",
            "CHST11",
            "MYB",
            "ZCCHC8",
            "MKL1",
            "IRS4",
            "SMC1A",
            "HSP90AB1",
            "TCL1A",
            "APC",
            "FBXO11",
            "ROBO2",
            "NCOA2",
            "NSD3",
            "BRD4",
            "DNMT3A",
            "SFRP4",
            "NF2",
            "CCNE1",
            "FANCD2",
            "MSH6",
            "ATR",
            "FLNA",
            "CTNNA2",
            "OLIG2",
            "RGS7",
            "TET1",
            "ACVR1",
            "HOXA9",
            "SDHB",
            "TCF12",
            "FAM135B",
            "NPM1",
            "ELF4",
            "COL3A1",
            "AKT3",
            "SS18",
            "POLE",
            "HIP1",
            "PDGFRA",
            "RALGDS",
            "FES",
            "AKT2",
            "ARAF",
            "ACKR3",
            "CDKN1A",
            "TLX3",
            "BUB1B",
            "MALT1",
            "CXCR4",
            "CASP8",
            "GNAS",
            "MLLT3",
            "FEV",
            "SMAD4",
            "CHD4",
            "FLT3",
            "NKX2-1",
            "FKBP9",
            "NT5C2",
            "ZBTB16",
            "ITK",
            "PHF6",
            "FAM46C",
            "FUBP1",
            "H3F3A",
            "LASP1",
            "PTPRT",
            "IGK",
            "PATZ1",
            "BIRC6",
            "RARA",
            "KIAA1549",
            "VAV1",
            "BCL7A",
            "TFEB",
            "XPA",
            "KMT2A",
            "NCOA1",
            "ZNF384",
            "QKI",
            "PABPC1",
            "TAF15",
            "FOXO3",
            "BMP5",
            "SSX2",
            "LRP1B",
            "RBM15",
            "HOXD13",
            "MNX1",
            "SDHAF2",
            "TMPRSS2",
            "ELL",
            "EPHA3",
            "PRDM16",
            "IL2",
            "PDCD1LG2",
            "JUN",
            "SPOP",
            "BCLAF1",
            "IKZF1",
            "MUTYH",
            "KAT7",
            "ATP2B3",
            "LYL1",
            "HMGA2",
            "PALB2",
            "HERPUD1",
            "FOXO4",
            "PPP6C",
            "ARID1B",
            "NTHL1",
            "GPC3",
            "PIK3R1",
            "LCK",
            "RPN1",
            "SS18L1",
            "HNRNPA2B1",
            "CEP89",
            "ETV6",
            "FOXO1",
            "PICALM",
            "TCEA1",
            "STK11",
            "HMGA1",
            "IDH2",
            "MYOD1",
            "KEAP1",
            "SDHC",
            "GNA11",
            "TAL1",
            "PTPRB",
            "CNTNAP2",
            "HOOK3",
            "PCM1",
            "MLLT1",
            "ISX",
            "GMPS",
            "SSX4",
            "ETV4",
            "ZMYM3",
            "PDGFRB",
            "TCF7L2",
            "SLC34A2",
            "CREB3L1",
            "CHD2",
            "UBR5",
            "BCL11B",
            "MYD88",
            "CSF1R",
            "NUTM2B",
            "CDH1",
            "MAP3K1",
            "TERT",
            "PBRM1",
            "MET",
            "NUTM1",
            "CCDC6",
            "GOLGA5",
            "PAX7",
            "PRDM2",
            "MYH11",
            "MAML3",
            "EPS15",
            "FAT3",
            "GATA1",
            "PCBP1",
            "NOTCH1",
            "MTCP1",
            "DDX6",
            "MED12",
            "MITF",
            "ARNT",
            "PAFAH1B2",
            "ATIC",
            "ELF3",
            "RHOH",
            "RPL22",
            "ERCC3",
            "CD79B",
            "ITGAV",
            "KDM5C",
            "BCL9L",
            "DDX3X",
            "LMO2",
            "NCOR1",
            "MUC4",
            "TPR",
            "SOCS1",
            "BIRC3",
            "MLLT6",
            "CDC73",
            "CTNNB1",
            "DCC",
            "CD74",
            "CTNND1",
            "NCOA4",
            "STAT3",
            "CDH11",
            "ARHGAP5",
            "ASXL1",
            "C15orf65",
            "WNK2",
            "U2AF1",
            "BMPR1A",
            "ERG",
        },
    )
    def second_gene_symbol(self, value):
        self._set_property("second_gene_symbol", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def specialized_molecular_test(self, value):
        self._set_property("specialized_molecular_test", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "miRNA",
            "DNA",
            "Total RNA",
            "mRNA",
            "Not Reported",
            "Protein",
        },
    )
    def test_analyte_type(self, value):
        self._set_property("test_analyte_type", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "Low",
            "Equivocal",
            "Normal",
            "Positive",
            "Negative",
            "Stable",
            "Not Reported",
            "Copy Number Reported",
            "Intermediate",
            "Amplified",
            "High",
            "Not Amplified",
            "Overexpressed",
            "Test Value Reported",
            "Loss of Expression",
            "Elevated",
            "Abnormal, NOS",
        },
    )
    def test_result(self, value):
        self._set_property("test_result", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "ukat/L",
            "mm^2",
            "U/g Hb",
            "x10^9 cells/L",
            "mU/mol Hb",
            "mg/dL",
            "mg/24 hr",
            "U/mL",
            "Not Reported",
            "mg/L",
            "mmol/L",
            "umol/L",
            "count x10^9/L",
            "percent",
            "mcg/mL",
            "U/L",
            "cells/mL",
            "g/L",
            "mcg/L",
            "g/dL",
            "ng/mL",
            "x10^3 cells/mcL",
        },
    )
    def test_units(self, value):
        self._set_property("test_units", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def test_value(self, value):
        self._set_property("test_value", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str, enum={"76-100", "26-50", "Not Reported", "0-25", "51-75"}
    )
    def test_value_range(self, value):
        self._set_property("test_value_range", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Not Reported",
            "End of Treatment Course 1",
            "End of Treatment Course 2",
            "End of Consolidation Therapy",
        },
    )
    def timepoint_category(self, value):
        self._set_property("timepoint_category", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def transcript(self, value):
        self._set_property("transcript", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Unknown", "Germline", "Somatic"})
    def variant_origin(self, value):
        self._set_property("variant_origin", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "Rearrangement",
            "Deletion",
            "Gain",
            "Insertion",
            "Substitution",
            "Conversion",
            "Splice",
            "Chrimerism",
            "Mosaicism",
            "Hypermethylation",
            "Not Reported",
            "Deletion-Insertion",
            "Mutation, NOS",
            "Duplication",
            "Internal Tandem Duplication",
            "Fusion",
            "Methylation",
            "Loss",
            "Inversion",
            "Extension",
            "Genetic Polymorphism",
            "Translocation",
            "Repeated Sequences",
            "Amplification",
            "Partial Methylation",
            "Alleles",
            "Other",
        },
    )
    def variant_type(self, value):
        self._set_property("variant_type", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "Heterozygous",
            "Homozygous",
            "Hemizygous",
            "Not Reported",
            "Nullizygous",
        },
    )
    def zygosity(self, value):
        self._set_property("zygosity", value)  # type: ignore  # inherited from CommonBase


datetime_hooks.cls_inject_created_datetime_hook(MolecularTest)
datetime_hooks.cls_inject_updated_datetime_hook(MolecularTest)
