from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class MolecularTest(base.Node):
    __tablename__: str = "node_moleculartest"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [["project_id", "submitter_id"]]

    # _defaults: default value for specified fields in the dictionary
    _defaults: Dict[str, Union[bool, float, int, str]] = {"state": "validated"}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {
        "title": "Molecular Test",
        "namespace": "https://gdc.cancer.gov",
        "category": "clinical",
        "submittable": True,
        "downloadable": False,
        "description": "Information pertaining to any molecular tests performed on the patient during a clinical event.",
        "required": [
            "submitter_id",
            "gene_symbol",
            "molecular_analysis_method",
            "test_result",
        ],
        "project": "*",
        "program": "*",
        "previous_version_downloadable": False,
    }

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "molecular_test"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
            "annotations": {
                "name": "molecular_tests",
                "src_type": base.Node.get_subclass("annotation"),
            },
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
            "annotations": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("annotation"),
            },
            "diagnoses": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("diagnosis"),
            },
            "follow_ups": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("follow_up"),
            },
            "slides": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("slide"),
            },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
            "diagnoses": {
                "edge_out": "_MolecularTestRelatedToDiagnosis_out",
                "dst_type": base.Node.get_subclass("diagnosis"),
            },
            "follow_ups": {
                "edge_out": "_MolecularTestPerformedAtFollowUp_out",
                "dst_type": base.Node.get_subclass("follow_up"),
            },
            "slides": {
                "edge_out": "_MolecularTestRelatedToSlide_out",
                "dst_type": base.Node.get_subclass("slide"),
            },
        }

    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False

    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(
                "{} not bound to a session. Try .get_versions(session).".format(self)
            )
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )

    @psqlgraph.pg_property(str)
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "validating",
            "suppressed",
            "live",
            "submitted",
            "error",
            "validated",
            "md5summing",
            "uploaded",
            "uploading",
            "released",
            "md5summed",
            "redacted",
            "invalid",
        },
    )
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, type(None))
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, type(None))
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def aa_change(self, value):
        self._set_property("aa_change", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "CA-125",
            "CD22",
            "TAG-72",
            "Immunoglobulin, Surface",
            "CD34",
            "CD3",
            "CD7",
            "CD138",
            "Unknown",
            "Squamous Cell Carcinoma Antigen (SCCA)",
            "CEA",
            "Mesothelin",
            "Immunoglobulin, Cytoplasmic",
            "CD79A",
            "CCND1",
            "CD56",
            "HLA-DR",
            "CD117",
            "CD14",
            "CD15",
            "CD23",
            "Ki67",
            "CD19",
            "CD25",
            "CD30",
            "NSE",
            "CD5",
            "CD33",
            "Lambda, Surface",
            "CA19-9",
            "Kappa, Surface",
            "FMC-7",
            "CD20",
            "CD45",
            "CD10",
            "Not Reported",
            "Prostate-Specific Antigen (PSA)",
            "BCL6",
        },
    )
    def antigen(self, value):
        self._set_property("antigen", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Trisomy", "Monosomy"})
    def aneuploidy(self, value):
        self._set_property("aneuploidy", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Pleural Fluid",
            "Uninvolved Tissue, NOS",
            "Blood",
            "Plasma",
            "Feces",
            "Bone Marrow",
            "Soft Tissue",
            "Embryonic Tissue",
            "Cerebrospinal Fluid",
            "Peritoneal Fluid",
            "Saliva",
            "Serum",
            "Unknown",
            "Buffy Coat",
            "Involved Tissue, NOS",
            "Granulocyte",
            "Tissue, NOS",
            "Urine",
            "Muscle Tissue",
            "Embryonic Fluid",
            "Connective Tissue",
            "Nerve Tissue",
            "Not Reported",
            "Buccal Mucosa",
            "Skin",
        },
    )
    def biospecimen_type(self, value):
        self._set_property("biospecimen_type", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int, float)
    def biospecimen_volume(self, value):
        self._set_property("biospecimen_volume", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int, float)
    def blood_test_normal_range_lower(self, value):
        self._set_property("blood_test_normal_range_lower", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int, float)
    def blood_test_normal_range_upper(self, value):
        self._set_property("blood_test_normal_range_upper", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def cell_count(self, value):
        self._set_property("cell_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "chr4",
            "chr6",
            "chr16",
            "chrM",
            "chr1",
            "chr19",
            "chr17",
            "chr15",
            "chr22",
            "chr7",
            "chr8",
            "chr10",
            "chr11",
            "chr5",
            "chr21",
            "chrX",
            "chrY",
            "Unknown",
            "chr13",
            "chr20",
            "chr12",
            "chr2",
            "chr14",
            "chr18",
            "chr3",
            "Not Reported",
            "chr9",
            "chr23",
        },
    )
    def chromosome(self, value):
        self._set_property("chromosome", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int, float)
    def copy_number(self, value):
        self._set_property("copy_number", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Non-clonal", "Clonal"})
    def clonality(self, value):
        self._set_property("clonality", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "t(10;11)(p11.2;q23)",
            "Unknown",
            "t(8;21)",
            "t(6;11)(q27;q23)",
            "t(3;5)(q25;q34)",
            "t(6;9)",
            "t(11;19)(q23;p13.1)",
            "Not Reported",
            "t(9;11)(p22;q23)",
        },
    )
    def chromosomal_translocation(self, value):
        self._set_property("chromosomal_translocation", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"q", "p", "Not Reported"})
    def chromosome_arm(self, value):
        self._set_property("chromosome_arm", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def cytoband(self, value):
        self._set_property("cytoband", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def days_to_test(self, value):
        self._set_property("days_to_test", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def exon(self, value):
        self._set_property("exon", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "NUTM1",
            "HIST1H4I",
            "TFE3",
            "MECOM",
            "CCND3",
            "NSD3",
            "GATA3",
            "PPP2R1A",
            "CD274",
            "TSC1",
            "HOXC11",
            "RB1",
            "SDHD",
            "CCND2",
            "ZNF444",
            "ELK4",
            "ATRX",
            "KAT6A",
            "IL2",
            "HMGA2",
            "PHOX2B",
            "RABEP1",
            "FANCA",
            "STK11",
            "TAF15",
            "TP53",
            "POLG",
            "TNFRSF14",
            "IKZF1",
            "KMT2D",
            "POLD1",
            "ERC1",
            "JAK1",
            "PPFIBP1",
            "SBDS",
            "KLF6",
            "CDKN1A",
            "SOCS1",
            "SMO",
            "FAM46C",
            "ARNT",
            "MNX1",
            "HOXB1",
            "SPOP",
            "FANCF",
            "TSHR",
            "DCTN1",
            "SSX2",
            "Not Reported",
            "TCF7L2",
            "PBX1",
            "BCL2L12",
            "PRDM2",
            "SS18L1",
            "CASP8",
            "H3F3B",
            "NSD2",
            "FOXO1",
            "TBL1XR1",
            "BCORL1",
            "QKI",
            "CDKN2C",
            "FLI1",
            "LHFP",
            "MB21D2",
            "RAD21",
            "CHCHD7",
            "PBRM1",
            "EIF1AX",
            "PIK3R1",
            "LZTR1",
            "SRSF3",
            "EZH2",
            "EPS15",
            "PER1",
            "GMPS",
            "GRM3",
            "RHOH",
            "PRKAR1A",
            "ELF3",
            "ERBB4",
            "BMP5",
            "FUBP1",
            "MTOR",
            "CHD2",
            "AR",
            "KRT7",
            "BCL6",
            "RUNX1T1",
            "ACSL6",
            "EGFR",
            "MSI2",
            "MAML3",
            "MSH2",
            "TFG",
            "SPECC1",
            "RAD51B",
            "ISX",
            "ROBO2",
            "CIITA",
            "P2RY8",
            "S100A7",
            "NUP98",
            "MALT1",
            "ITGAV",
            "Unknown",
            "SOX2",
            "SPEN",
            "CUL3",
            "DNM2",
            "ID3",
            "HOXC13",
            "ZFHX3",
            "TOP1",
            "CBFA2T3",
            "CCND1",
            "CD79A",
            "GAS7",
            "CDK12",
            "LRIG3",
            "AMER1",
            "MAF",
            "PDE4DIP",
            "BRAF",
            "FAM47C",
            "ACSL3",
            "MLLT1",
            "PTPRK",
            "LMNA",
            "SRSF2",
            "CREB3L1",
            "BRIP1",
            "ELF4",
            "MEN1",
            "IDH1",
            "IKBKB",
            "RAF1",
            "FKBP9",
            "PRKCB",
            "RAC1",
            "PTK6",
            "CRNKL1",
            "ARHGAP5",
            "ECT2L",
            "FANCD2",
            "FLNA",
            "CLIP1",
            "PRRX1",
            "TSC2",
            "NTRK1",
            "IDH2",
            "CLP1",
            "FLT4",
            "MSH6",
            "TGFBR2",
            "OLIG2",
            "POLQ",
            "AFF1",
            "COL2A1",
            "NIN",
            "NCOA1",
            "SMAD2",
            "PAX3",
            "RPL10",
            "ERCC4",
            "AKT2",
            "NCKIPSD",
            "RALGDS",
            "B2M",
            "HEY1",
            "SMARCA4",
            "CHIC2",
            "CYSLTR2",
            "MAP2K1",
            "NRAS",
            "PRPF40B",
            "ALK",
            "TRB",
            "CIC",
            "LEF1",
            "SND1",
            "BRD4",
            "NCOR2",
            "OMD",
            "MYH11",
            "BAP1",
            "EPHA3",
            "FAS",
            "ASXL1",
            "GLI1",
            "MYB",
            "MUC16",
            "SEPT5",
            "BCL9",
            "CDKN2A",
            "ACVR2A",
            "FSTL3",
            "FGFR3",
            "MAP2K2",
            "TAL2",
            "TFRC",
            "MLLT11",
            "BIRC3",
            "NCOR1",
            "CNBD1",
            "PAX5",
            "ETNK1",
            "ZBTB16",
            "ANK1",
            "CTNNA2",
            "SIRPA",
            "MLH1",
            "PTPN11",
            "LYL1",
            "ETV5",
            "ALDH2",
            "SUFU",
            "MUTYH",
            "MLLT10",
            "DDB2",
            "POU2AF1",
            "COL1A1",
            "XPA",
            "HOXA13",
            "MAP3K13",
            "HOXA9",
            "CSF3R",
            "PMS1",
            "AQP1",
            "CYLD",
            "PRF1",
            "CALR",
            "SHTN1",
            "TRIM27",
            "TFEB",
            "DDX5",
            "CNTNAP2",
            "KRT20",
            "TCL1A",
            "KAT7",
            "NT5C2",
            "RUNX1",
            "BCL11B",
            "RAP1GDS1",
            "DICER1",
            "HNRNPA2B1",
            "MDS2",
            "ERCC3",
            "CARD11",
            "Not Applicable",
            "CTNND1",
            "FEN1",
            "HOXD13",
            "EED",
            "KDM5A",
            "EBF1",
            "HNF1A",
            "MUC1",
            "NKX2-1",
            "CHGA",
            "HRAS",
            "ROS1",
            "A1CF",
            "ATM",
            "SSX4",
            "TEC",
            "KNSTRN",
            "HIF1A",
            "LIFR",
            "EZR",
            "GCET1",
            "SLC34A2",
            "CDKN1B",
            "ABI1",
            "CD28",
            "KNL1",
            "DEK",
            "GATA1",
            "CD99",
            "ARHGEF12",
            "YWHAE",
            "NPM1",
            "BCL7A",
            "NOTCH2",
            "UBR5",
            "IGL",
            "TRAF7",
            "CCDC6",
            "TAL1",
            "DDR2",
            "PICALM",
            "ZNF384",
            "JUN",
            "CBL",
            "RPL22",
            "TLX3",
            "MSN",
            "DDX3X",
            "TPM4",
            "RGS7",
            "C15orf65",
            "NFKB2",
            "ELL",
            "MITF",
            "TP63",
            "LMO2",
            "ASPSCR1",
            "BRD3",
            "AKT1",
            "ATR",
            "SDHB",
            "CACNA1D",
            "FAT3",
            "DNTT",
            "BMPR1A",
            "ETV6",
            "PGR",
            "JAK3",
            "ZMYM3",
            "EXT1",
            "NUP214",
            "PPP6C",
            "KDM5C",
            "HSP90AA1",
            "BRCA2",
            "CTNNB1",
            "SRGAP3",
            "NRG1",
            "FOXP1",
            "NFIB",
            "AXIN2",
            "CANT1",
            "FCGR2B",
            "PIK3CB",
            "GNAQ",
            "PHF6",
            "SALL4",
            "POU5F1",
            "FUS",
            "NUTM2A",
            "RSPO3",
            "NFE2L2",
            "PTPN13",
            "KIAA1549",
            "MYH9",
            "CRTC1",
            "KIT",
            "SGK1",
            "BCLAF1",
            "BLM",
            "SUZ12",
            "DCAF12L2",
            "TNFAIP3",
            "STRN",
            "ABL1",
            "CRTC3",
            "HMGN2P46",
            "DGCR8",
            "FOXA1",
            "PDGFRA",
            "FANCC",
            "FOXL2",
            "JAK2",
            "NDRG1",
            "WWTR1",
            "AFF3",
            "PABPC1",
            "FGFR1",
            "LMO1",
            "RSPO2",
            "SMARCD1",
            "STAG1",
            "PDGFB",
            "PCM1",
            "STAT6",
            "MAP3K1",
            "KDSR",
            "EML4",
            "ARAF",
            "NF2",
            "CREBBP",
            "SH3GL1",
            "CREB3L2",
            "KMT2C",
            "CHST11",
            "EPAS1",
            "NBN",
            "ABL2",
            "HIP1",
            "PIK3CA",
            "AXIN1",
            "ARID1A",
            "ATIC",
            "COL3A1",
            "CSMD3",
            "CHD4",
            "CYP2C8",
            "CDK4",
            "FANCE",
            "SEPT9",
            "FES",
            "MLLT3",
            "DNMT3A",
            "NSD1",
            "ATP1A1",
            "RGPD3",
            "STAT5B",
            "TMEM127",
            "CBFB",
            "NBEA",
            "MAP2K4",
            "FCRL4",
            "BCL10",
            "PAX8",
            "ARHGAP26",
            "PTCH1",
            "NFKBIE",
            "CDK6",
            "PWWP2A",
            "DROSHA",
            "DDIT3",
            "MYOD1",
            "MLF1",
            "MPL",
            "CNBP",
            "SYK",
            "CBLB",
            "SH2B3",
            "KTN1",
            "PML",
            "PTEN",
            "LRP1B",
            "U2AF1",
            "CREB1",
            "CDH11",
            "MN1",
            "GOLGA5",
            "RET",
            "MED12",
            "FOXO3",
            "TNC",
            "CRLF2",
            "HSP90AB1",
            "EWSR1",
            "ATF1",
            "JAZF1",
            "TNFRSF17",
            "PALB2",
            "TRRAP",
            "TCF12",
            "TERT",
            "ZCCHC8",
            "SSX1",
            "GATA2",
            "ARID2",
            "HMGA1",
            "TCEA1",
            "H3F3A",
            "SMAD4",
            "DAXX",
            "MAX",
            "FHIT",
            "PAX7",
            "EPHA7",
            "STIL",
            "DUX4L1",
            "SMAD3",
            "PLCG1",
            "REL",
            "KLF4",
            "CTNND2",
            "AKT3",
            "NCOA2",
            "LARP4B",
            "PRDM16",
            "CEP89",
            "SNX29",
            "TPM3",
            "KLK2",
            "STAG2",
            "AKAP9",
            "IRS4",
            "GPC3",
            "GNAS",
            "ESR1",
            "MGMT",
            "CSF1R",
            "FGFR2",
            "CD74",
            "CDC73",
            "ZNF521",
            "BIRC6",
            "ZNF479",
            "WRN",
            "MKL1",
            "CHEK2",
            "KEAP1",
            "PTPRT",
            "SET",
            "CTCF",
            "PREX2",
            "SMARCB1",
            "SMARCE1",
            "CNOT3",
            "RARA",
            "ARID1B",
            "DNAJB1",
            "HLA-A",
            "POT1",
            "CCNC",
            "NR4A3",
            "DCC",
            "EPCAM",
            "FBXW7",
            "CD79B",
            "HLF",
            "KDR",
            "BCR",
            "FANCG",
            "CLTC",
            "BCL2",
            "SETBP1",
            "MLH2",
            "TBX3",
            "MLLT6",
            "USP8",
            "ELN",
            "BTK",
            "CDX2",
            "IL21R",
            "PRCC",
            "PRDM1",
            "LCK",
            "LPP",
            "CDH1",
            "PIM1",
            "TLR2",
            "SYP",
            "TRA",
            "TLX1",
            "TMPRSS2",
            "TPR",
            "MAML2",
            "TRIP11",
            "MYD88",
            "SDC4",
            "KDM6A",
            "SEPT6",
            "FIP1L1",
            "PLAG1",
            "NF1",
            "POLE",
            "PTGS2",
            "MYO5A",
            "NCOA4",
            "HIST1H3B",
            "VAV1",
            "DDX6",
            "FGFR4",
            "STAT3",
            "MAFB",
            "KCNJ5",
            "MYCL",
            "NFATC2",
            "CLTCL1",
            "CCNB1IP1",
            "FAM135B",
            "COX6C",
            "PMS2",
            "KIF5B",
            "LCP1",
            "RMI2",
            "APC",
            "GOPC",
            "ZRSR2",
            "CCR7",
            "FAT4",
            "TCF3",
            "SDHA",
            "CAMTA1",
            "HERPUD1",
            "RNF43",
            "GNA11",
            "FBXO11",
            "ATP2B3",
            "SMC1A",
            "ERBB3",
            "CXCR4",
            "BCL11A",
            "MYC",
            "PDGFRB",
            "KRAS",
            "PDCD1LG2",
            "ITK",
            "FEV",
            "PATZ1",
            "CEBPA",
            "NONO",
            "IGK",
            "HOXA11",
            "SETD2",
            "WT1",
            "FBLN2",
            "FOXO4",
            "USP6",
            "RNF213",
            "BCOR",
            "FH",
            "ERCC5",
            "WNK2",
            "PTPN6",
            "DDX10",
            "SKI",
            "ZNF429",
            "BRCA1",
            "CBLC",
            "XPO1",
            "NUTM2B",
            "FNBP1",
            "NAB2",
            "KMT2A",
            "MDM2",
            "MAPK1",
            "ZEB1",
            "PTPRB",
            "MALAT1",
            "SFRP4",
            "CD209",
            "FOXR1",
            "TET1",
            "ASXL2",
            "GRIN2A",
            "RPL5",
            "RECQL4",
            "BUB1B",
            "APOBEC3B",
            "ERCC2",
            "IRF4",
            "ERBB2",
            "PAFAH1B2",
            "XPC",
            "EIF3E",
            "RANBP2",
            "TRIM33",
            "ETV4",
            "EIF4A2",
            "SLC45A3",
            "WAS",
            "AFF4",
            "SFPQ",
            "MUC4",
            "PDPN",
            "MDM4",
            "NOTCH1",
            "VHL",
            "PRKACA",
            "ZNF198",
            "CDH10",
            "SDHAF2",
            "RBM10",
            "BTG1",
            "PPM1D",
            "ACVR1",
            "EXT2",
            "ZNF331",
            "HOXD11",
            "KAT6B",
            "TRIM24",
            "FLCN",
            "BARD1",
            "NUMA1",
            "MYCN",
            "MET",
            "FAT1",
            "CCR4",
            "FGFR1OP",
            "TET2",
            "ZNRF3",
            "SS18",
            "IL6ST",
            "ACKR3",
            "IGH",
            "CNTRL",
            "IL7R",
            "EP300",
            "PSIP1",
            "VTI1A",
            "GPHN",
            "CALB2",
            "RBM15",
            "LASP1",
            "PCBP1",
            "FAM131B",
            "SF3B1",
            "BCL9L",
            "SRC",
            "RPN1",
            "THRAP3",
            "CARS",
            "NTRK3",
            "ERG",
            "FLT3",
            "RHOA",
            "WIF1",
            "MLLT4",
            "SDHC",
            "TRD",
            "PPARG",
            "MIB1",
            "MTCP1",
            "ETV1",
            "NTHL1",
            "WDCP",
            "TFPT",
            "NACA",
            "CCNE1",
            "CUX1",
            "HOOK3",
            "PTPRC",
            "LSM14A",
            "CDH17",
            "IGKC",
            "BCL3",
        },
    )
    def gene_symbol(self, value):
        self._set_property("gene_symbol", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"H3", "Unknown", "H1", "H4", "H2A", "H2B", "Not Reported"})
    def histone_family(self, value):
        self._set_property("histone_family", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "H3.5",
            "H2A.X",
            "H3.2",
            "mH2A",
            "H2A.Z.1",
            "H3t (H3.4)",
            "H2A.Z",
            "mH2A.1",
            "H3.1",
            "mH2A.2",
            "H3.X",
            "Unknown",
            "H3.Y",
            "H2A.Z.2.2",
            "H2A.Z.2",
            "Not Reported",
            "H2A-Bbd",
            "H3.3",
            "CENP-A",
        },
    )
    def histone_variant(self, value):
        self._set_property("histone_variant", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "HPV51",
            "HPV39",
            "HPV66",
            "HPV31",
            "HPV35",
            "HPV68",
            "HPV58",
            "HPV56",
            "HPV18",
            "HPV45",
            "HPV16",
            "HPV73",
            "HPV59",
            "HPV52",
            "HPV33",
        },
    )
    def hpv_strain(self, value):
        self._set_property("hpv_strain", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def intron(self, value):
        self._set_property("intron", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Metaphase Nucleus Count",
            "Alpha Fetoprotein",
            "Immunoglobulin A",
            "Minimal Residual Disease",
            "Total Bilirubin",
            "Myeloblasts",
            "M Protein",
            "Beta 2 Microglobulin",
            "Lymphoblasts",
            "5-Hydroxyindoleacetic Acid",
            "Cellularity",
            "Basophil",
            "Human Papillomavirus",
            "Cytokeratin 5",
            "Absolute Neutrophil",
            "Unknown",
            "Testosterone",
            "Serum Free Immunoglobulin Light Chain, NOS",
            "BG8",
            "Human Chorionic Gonadotropin",
            "Neutrophil Bands",
            "Serum Mesothelin",
            "Hemoglobin",
            "Promyelocytes",
            "Erythrocyte Sedimentation Rate",
            "Serum Free Immunoglobulin Light Chain, Lambda",
            "Calcium",
            "HPV-E6/E7",
            "Cytokeratin 6",
            "Creatinine",
            "Norepinephrine-Secreting",
            "Lymphocytes",
            "Immunoglobulin G",
            "Dopamine-Secreting",
            "Metanephrine-Secreting",
            "Methoxytyramine-Secreting",
            "Metamyelocytes",
            "Eosinophil",
            "Not Reported",
            "Chromogranin A",
            "Hematocrit",
            "TAG-72",
            "Circulating Tumor Cells",
            "Blood Urea Nitrogen",
            "Prolymphocytes",
            "Circulating Endothelial Cells",
            "Glucose",
            "Serum Free Immunoglobulin Light Chain, Kappa",
            "Luteinizing Hormone",
            "Lactate Dehydrogenase",
            "Myelocytes",
            "Promonocytes",
            "Microsatellite Instability",
            "Chromogranin B",
            "Segmented Neutrophil",
            "Epinephrine-Secreting",
            "Total Protein",
            "Albumin",
            "Blast Count",
            "C-Reactive Protein",
            "Monocytes",
            "Leukocytes",
            "Immunoglobulin M",
            "Gamma-Enolase",
            "Epstein-Barr Virus",
            "Normetanephrine-Secreting",
            "Platelets",
            "Prothrombin Time",
            "B-cell genotyping",
        },
    )
    def laboratory_test(self, value):
        self._set_property("laboratory_test", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def loci_abnormal_count(self, value):
        self._set_property("loci_abnormal_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def loci_count(self, value):
        self._set_property("loci_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def locus(self, value):
        self._set_property("locus", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Yes", "No", "Unknown", "Not Reported"})
    def mismatch_repair_mutation(self, value):
        self._set_property("mismatch_repair_mutation", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int, float)
    def mitotic_count(self, value):
        self._set_property("mitotic_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int, float)
    def mitotic_total_area(self, value):
        self._set_property("mitotic_total_area", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "RNA Sequencing",
            "Flow Cytometry",
            "Immunofluorescence",
            "Southern Blotting",
            "WGS",
            "Cytogenetics, NOS",
            "Microarray",
            "Other",
            "RT-PCR",
            "Karyotype",
            "ISH",
            "FISH",
            "Unknown",
            "Sequencing, NOS",
            "WXS",
            "Targeted Sequencing",
            "IHC",
            "Comparative Genomic Hybridization",
            "Microsatellite Analysis",
            "Not Reported",
            "Nuclear Staining",
            "PCR",
        },
    )
    def molecular_analysis_method(self, value):
        self._set_property("molecular_analysis_method", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "5 Prime UTR Variant",
            "TFBS Ablation",
            "Coding Sequence Variant",
            "Inframe Deletion",
            "Protein Altering Variant",
            "Intron Variant",
            "Incomplete Terminal Codon Variant",
            "Mature miRNA Variant",
            "Stop Retained Variant",
            "Regulatory Region Variant",
            "Upstream Gene Variant",
            "3 Prime UTR Variant",
            "Splice Acceptor Variant",
            "Missense Variant",
            "Non-coding Transcript Variant",
            "Feature Truncation",
            "Stop Gain",
            "Downstream Gene Variant",
            "Regulatory Region Amplification",
            "Synonymous Variant",
            "Regulatory Region Ablation",
            "TFBS Amplification",
            "TF Binding Site Variant",
            "Feature Elongation",
            "NMD Transcript Variant",
            "Splice Donor Variant",
            "Splice Region Variant",
            "Start Lost",
            "Intergenic Variant",
            "Frameshift Variant",
            "Transcript Ablation",
            "Transcript Amplification",
            "Exon Variant",
            "Non-coding Transcript Exon Variant",
            "Inframe Insertion",
            "Nonsense",
            "Stop Lost",
        },
    )
    def molecular_consequence(self, value):
        self._set_property("molecular_consequence", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"13", "12", "61"})
    def mutation_codon(self, value):
        self._set_property("mutation_codon", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Likely Benign",
            "Likely Pathogenic",
            "Benign",
            "Uncertain Significance",
            "Pathogenic",
        },
    )
    def pathogenicity(self, value):
        self._set_property("pathogenicity", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Aneuploid",
            "Unknown",
            "Diploid",
            "Hypodiploid",
            "Hyperdiploid",
            "Not Reported",
            "Tetraploid",
            "Near Diploid",
        },
    )
    def ploidy(self, value):
        self._set_property("ploidy", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def second_exon(self, value):
        self._set_property("second_exon", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "NUTM1",
            "HIST1H4I",
            "TFE3",
            "MECOM",
            "CCND3",
            "NSD3",
            "GATA3",
            "PPP2R1A",
            "CD274",
            "TSC1",
            "HOXC11",
            "RB1",
            "SDHD",
            "CCND2",
            "ZNF444",
            "ELK4",
            "ATRX",
            "KAT6A",
            "IL2",
            "HMGA2",
            "PHOX2B",
            "RABEP1",
            "FANCA",
            "STK11",
            "TAF15",
            "TP53",
            "POLG",
            "TNFRSF14",
            "IKZF1",
            "KMT2D",
            "POLD1",
            "ERC1",
            "JAK1",
            "PPFIBP1",
            "SBDS",
            "KLF6",
            "CDKN1A",
            "SOCS1",
            "SMO",
            "FAM46C",
            "ARNT",
            "MNX1",
            "HOXB1",
            "SPOP",
            "FANCF",
            "TSHR",
            "DCTN1",
            "SSX2",
            "Not Reported",
            "TCF7L2",
            "PBX1",
            "BCL2L12",
            "PRDM2",
            "SS18L1",
            "CASP8",
            "H3F3B",
            "NSD2",
            "FOXO1",
            "TBL1XR1",
            "BCORL1",
            "QKI",
            "CDKN2C",
            "FLI1",
            "LHFP",
            "MB21D2",
            "RAD21",
            "CHCHD7",
            "PBRM1",
            "EIF1AX",
            "PIK3R1",
            "LZTR1",
            "SRSF3",
            "EZH2",
            "EPS15",
            "PER1",
            "GMPS",
            "GRM3",
            "RHOH",
            "PRKAR1A",
            "ELF3",
            "ERBB4",
            "BMP5",
            "FUBP1",
            "MTOR",
            "CHD2",
            "AR",
            "BCL6",
            "RUNX1T1",
            "ACSL6",
            "EGFR",
            "MSI2",
            "MAML3",
            "MSH2",
            "TFG",
            "SPECC1",
            "RAD51B",
            "ISX",
            "ROBO2",
            "CIITA",
            "P2RY8",
            "S100A7",
            "NUP98",
            "MALT1",
            "ITGAV",
            "Unknown",
            "SOX2",
            "SPEN",
            "CUL3",
            "DNM2",
            "ID3",
            "HOXC13",
            "ZFHX3",
            "TOP1",
            "CBFA2T3",
            "CCND1",
            "CD79A",
            "GAS7",
            "CDK12",
            "LRIG3",
            "AMER1",
            "MAF",
            "PDE4DIP",
            "BRAF",
            "FAM47C",
            "ACSL3",
            "MLLT1",
            "PTPRK",
            "LMNA",
            "SRSF2",
            "CREB3L1",
            "BRIP1",
            "ELF4",
            "MEN1",
            "IDH1",
            "IKBKB",
            "RAF1",
            "FKBP9",
            "PRKCB",
            "RAC1",
            "PTK6",
            "CRNKL1",
            "ARHGAP5",
            "ECT2L",
            "FANCD2",
            "FLNA",
            "CLIP1",
            "PRRX1",
            "TSC2",
            "NTRK1",
            "IDH2",
            "CLP1",
            "FLT4",
            "MSH6",
            "TGFBR2",
            "OLIG2",
            "POLQ",
            "AFF1",
            "COL2A1",
            "NIN",
            "NCOA1",
            "SMAD2",
            "PAX3",
            "RPL10",
            "ERCC4",
            "AKT2",
            "NCKIPSD",
            "RALGDS",
            "B2M",
            "HEY1",
            "SMARCA4",
            "CHIC2",
            "CYSLTR2",
            "MAP2K1",
            "NRAS",
            "PRPF40B",
            "ALK",
            "TRB",
            "CIC",
            "LEF1",
            "SND1",
            "BRD4",
            "NCOR2",
            "OMD",
            "MYH11",
            "BAP1",
            "EPHA3",
            "FAS",
            "ASXL1",
            "GLI1",
            "MYB",
            "MUC16",
            "SEPT5",
            "BCL9",
            "CDKN2A",
            "ACVR2A",
            "FSTL3",
            "FGFR3",
            "MAP2K2",
            "TAL2",
            "TFRC",
            "MLLT11",
            "BIRC3",
            "NCOR1",
            "CNBD1",
            "PAX5",
            "ETNK1",
            "ZBTB16",
            "ANK1",
            "CTNNA2",
            "SIRPA",
            "MLH1",
            "PTPN11",
            "LYL1",
            "ETV5",
            "ALDH2",
            "SUFU",
            "MUTYH",
            "MLLT10",
            "DDB2",
            "POU2AF1",
            "COL1A1",
            "XPA",
            "HOXA13",
            "MAP3K13",
            "HOXA9",
            "CSF3R",
            "PMS1",
            "CYLD",
            "PRF1",
            "TRIM27",
            "CALR",
            "SHTN1",
            "TFEB",
            "DDX5",
            "CNTNAP2",
            "TCL1A",
            "KAT7",
            "NT5C2",
            "RUNX1",
            "BCL11B",
            "RAP1GDS1",
            "DICER1",
            "HNRNPA2B1",
            "MDS2",
            "ERCC3",
            "CARD11",
            "CTNND1",
            "FEN1",
            "HOXD13",
            "EED",
            "KDM5A",
            "EBF1",
            "HNF1A",
            "MUC1",
            "NKX2-1",
            "CHGA",
            "HRAS",
            "ROS1",
            "A1CF",
            "ATM",
            "SSX4",
            "TEC",
            "KNSTRN",
            "HIF1A",
            "LIFR",
            "EZR",
            "SLC34A2",
            "CDKN1B",
            "ABI1",
            "CD28",
            "KNL1",
            "DEK",
            "GATA1",
            "CD99",
            "ARHGEF12",
            "YWHAE",
            "NPM1",
            "BCL7A",
            "NOTCH2",
            "UBR5",
            "IGL",
            "TRAF7",
            "CCDC6",
            "TAL1",
            "DDR2",
            "PICALM",
            "ZNF384",
            "JUN",
            "CBL",
            "RPL22",
            "TLX3",
            "MSN",
            "DDX3X",
            "TPM4",
            "RGS7",
            "C15orf65",
            "NFKB2",
            "ELL",
            "MITF",
            "TP63",
            "LMO2",
            "ASPSCR1",
            "BRD3",
            "AKT1",
            "ATR",
            "SDHB",
            "CACNA1D",
            "FAT3",
            "BMPR1A",
            "ETV6",
            "PGR",
            "JAK3",
            "ZMYM3",
            "EXT1",
            "NUP214",
            "PPP6C",
            "KDM5C",
            "HSP90AA1",
            "BRCA2",
            "CTNNB1",
            "SRGAP3",
            "NRG1",
            "FOXP1",
            "NFIB",
            "AXIN2",
            "CANT1",
            "FCGR2B",
            "PIK3CB",
            "GNAQ",
            "PHF6",
            "SALL4",
            "POU5F1",
            "FUS",
            "NUTM2A",
            "RSPO3",
            "NFE2L2",
            "PTPN13",
            "KIAA1549",
            "MYH9",
            "CRTC1",
            "KIT",
            "SGK1",
            "BCLAF1",
            "BLM",
            "SUZ12",
            "DCAF12L2",
            "TNFAIP3",
            "STRN",
            "ABL1",
            "CRTC3",
            "HMGN2P46",
            "DGCR8",
            "FOXA1",
            "PDGFRA",
            "FANCC",
            "FOXL2",
            "JAK2",
            "NDRG1",
            "WWTR1",
            "AFF3",
            "PABPC1",
            "FGFR1",
            "LMO1",
            "RSPO2",
            "SMARCD1",
            "STAG1",
            "PDGFB",
            "PCM1",
            "STAT6",
            "MAP3K1",
            "KDSR",
            "EML4",
            "ARAF",
            "NF2",
            "CREBBP",
            "SH3GL1",
            "CREB3L2",
            "KMT2C",
            "CHST11",
            "EPAS1",
            "NBN",
            "ABL2",
            "HIP1",
            "PIK3CA",
            "AXIN1",
            "ARID1A",
            "ATIC",
            "COL3A1",
            "CSMD3",
            "CHD4",
            "CYP2C8",
            "CDK4",
            "FANCE",
            "SEPT9",
            "FES",
            "MLLT3",
            "DNMT3A",
            "NSD1",
            "ATP1A1",
            "RGPD3",
            "STAT5B",
            "TMEM127",
            "CBFB",
            "NBEA",
            "MAP2K4",
            "FCRL4",
            "BCL10",
            "PAX8",
            "ARHGAP26",
            "PTCH1",
            "NFKBIE",
            "CDK6",
            "PWWP2A",
            "DROSHA",
            "DDIT3",
            "MYOD1",
            "MLF1",
            "MPL",
            "CNBP",
            "SYK",
            "CBLB",
            "SH2B3",
            "KTN1",
            "PML",
            "PTEN",
            "LRP1B",
            "U2AF1",
            "CREB1",
            "CDH11",
            "MN1",
            "GOLGA5",
            "RET",
            "MED12",
            "FOXO3",
            "TNC",
            "CRLF2",
            "HSP90AB1",
            "EWSR1",
            "ATF1",
            "JAZF1",
            "TNFRSF17",
            "PALB2",
            "TRRAP",
            "TCF12",
            "TERT",
            "ZCCHC8",
            "SSX1",
            "GATA2",
            "ARID2",
            "HMGA1",
            "TCEA1",
            "H3F3A",
            "SMAD4",
            "DAXX",
            "MAX",
            "FHIT",
            "PAX7",
            "EPHA7",
            "STIL",
            "DUX4L1",
            "SMAD3",
            "PLCG1",
            "REL",
            "KLF4",
            "CTNND2",
            "AKT3",
            "NCOA2",
            "LARP4B",
            "PRDM16",
            "CEP89",
            "SNX29",
            "TPM3",
            "KLK2",
            "STAG2",
            "AKAP9",
            "IRS4",
            "GPC3",
            "GNAS",
            "ESR1",
            "MGMT",
            "CSF1R",
            "FGFR2",
            "CD74",
            "CDC73",
            "ZNF521",
            "BIRC6",
            "ZNF479",
            "WRN",
            "MKL1",
            "CHEK2",
            "KEAP1",
            "PTPRT",
            "SET",
            "CTCF",
            "PREX2",
            "SMARCB1",
            "SMARCE1",
            "CNOT3",
            "RARA",
            "ARID1B",
            "DNAJB1",
            "HLA-A",
            "POT1",
            "CCNC",
            "NR4A3",
            "DCC",
            "FBXW7",
            "HLF",
            "CD79B",
            "KDR",
            "BCR",
            "FANCG",
            "CLTC",
            "BCL2",
            "SETBP1",
            "MLH2",
            "TBX3",
            "MLLT6",
            "USP8",
            "ELN",
            "BTK",
            "CDX2",
            "IL21R",
            "PRCC",
            "PRDM1",
            "LCK",
            "LPP",
            "CDH1",
            "PIM1",
            "TLR2",
            "SYP",
            "TRA",
            "TLX1",
            "TMPRSS2",
            "TPR",
            "MAML2",
            "TRIP11",
            "MYD88",
            "SDC4",
            "KDM6A",
            "SEPT6",
            "FIP1L1",
            "PLAG1",
            "NF1",
            "POLE",
            "MYO5A",
            "NCOA4",
            "HIST1H3B",
            "VAV1",
            "DDX6",
            "FGFR4",
            "STAT3",
            "MAFB",
            "KCNJ5",
            "MYCL",
            "NFATC2",
            "CLTCL1",
            "CCNB1IP1",
            "FAM135B",
            "COX6C",
            "PMS2",
            "KIF5B",
            "LCP1",
            "RMI2",
            "APC",
            "GOPC",
            "ZRSR2",
            "CCR7",
            "FAT4",
            "TCF3",
            "SDHA",
            "CAMTA1",
            "HERPUD1",
            "RNF43",
            "GNA11",
            "FBXO11",
            "ATP2B3",
            "SMC1A",
            "ERBB3",
            "CXCR4",
            "BCL11A",
            "MYC",
            "PDGFRB",
            "KRAS",
            "PDCD1LG2",
            "ITK",
            "FEV",
            "PATZ1",
            "CEBPA",
            "NONO",
            "IGK",
            "HOXA11",
            "SETD2",
            "WT1",
            "FBLN2",
            "FOXO4",
            "USP6",
            "RNF213",
            "BCOR",
            "FH",
            "ERCC5",
            "WNK2",
            "PTPN6",
            "DDX10",
            "SKI",
            "ZNF429",
            "BRCA1",
            "CBLC",
            "XPO1",
            "NUTM2B",
            "FNBP1",
            "NAB2",
            "KMT2A",
            "MDM2",
            "MAPK1",
            "ZEB1",
            "PTPRB",
            "MALAT1",
            "SFRP4",
            "CD209",
            "FOXR1",
            "TET1",
            "ASXL2",
            "GRIN2A",
            "RPL5",
            "RECQL4",
            "BUB1B",
            "APOBEC3B",
            "ERCC2",
            "IRF4",
            "ERBB2",
            "PAFAH1B2",
            "XPC",
            "EIF3E",
            "RANBP2",
            "TRIM33",
            "ETV4",
            "EIF4A2",
            "SLC45A3",
            "WAS",
            "AFF4",
            "SFPQ",
            "MUC4",
            "MDM4",
            "NOTCH1",
            "VHL",
            "PRKACA",
            "ZNF198",
            "CDH10",
            "SDHAF2",
            "RBM10",
            "BTG1",
            "PPM1D",
            "ACVR1",
            "EXT2",
            "ZNF331",
            "HOXD11",
            "KAT6B",
            "TRIM24",
            "FLCN",
            "BARD1",
            "NUMA1",
            "MYCN",
            "MET",
            "FAT1",
            "CCR4",
            "FGFR1OP",
            "TET2",
            "ZNRF3",
            "SS18",
            "IL6ST",
            "ACKR3",
            "IGH",
            "CNTRL",
            "IL7R",
            "EP300",
            "PSIP1",
            "VTI1A",
            "GPHN",
            "RBM15",
            "LASP1",
            "PCBP1",
            "FAM131B",
            "SF3B1",
            "BCL9L",
            "SRC",
            "RPN1",
            "THRAP3",
            "CARS",
            "NTRK3",
            "ERG",
            "FLT3",
            "RHOA",
            "WIF1",
            "MLLT4",
            "SDHC",
            "TRD",
            "PPARG",
            "MTCP1",
            "ETV1",
            "NTHL1",
            "WDCP",
            "TFPT",
            "NACA",
            "CCNE1",
            "CUX1",
            "HOOK3",
            "PTPRC",
            "LSM14A",
            "CDH17",
            "BCL3",
        },
    )
    def second_gene_symbol(self, value):
        self._set_property("second_gene_symbol", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def specialized_molecular_test(self, value):
        self._set_property("specialized_molecular_test", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "mRNA",
            "Unknown",
            "Not Reported",
            "miRNA",
            "Protein",
            "DNA",
            "Total RNA",
        },
    )
    def test_analyte_type(self, value):
        self._set_property("test_analyte_type", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Equivocal",
            "Amplified",
            "Copy Number Reported",
            "Normal",
            "Low",
            "Not Amplified",
            "Abnormal, NOS",
            "Stable",
            "Positive",
            "Intermediate",
            "Unknown",
            "Loss of Expression",
            "High",
            "Negative",
            "Elevated",
            "Not Reported",
            "Overexpressed",
            "Test Value Reported",
        },
    )
    def test_result(self, value):
        self._set_property("test_result", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "ukat/L",
            "mg/24 hr",
            "g/L",
            "U/g Hb",
            "x10^3 cells/mcL",
            "ng/mL",
            "U/mL",
            "mg/L",
            "mg/dL",
            "mcg/mL",
            "mmol/L",
            "mcg/L",
            "count x10^9/L",
            "Unknown",
            "mU/mol Hb",
            "percent",
            "U/L",
            "g/dL",
            "umol/L",
            "mm^2",
            "x10^9 cells/L",
            "Not Reported",
            "cells/mL",
        },
    )
    def test_units(self, value):
        self._set_property("test_units", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int, float)
    def test_value(self, value):
        self._set_property("test_value", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"76-100", "0-25", "Not Reported", "51-75", "26-50"})
    def test_value_range(self, value):
        self._set_property("test_value_range", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "End of Treatment Course 1",
            "End of Treatment Course 2",
            "Not Reported",
            "End of Consolidation Therapy",
        },
    )
    def timepoint_category(self, value):
        self._set_property("timepoint_category", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def transcript(self, value):
        self._set_property("transcript", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Unknown", "Somatic", "Germline"})
    def variant_origin(self, value):
        self._set_property("variant_origin", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Insertion",
            "Deletion",
            "Chrimerism",
            "Loss",
            "Repeated Sequences",
            "Conversion",
            "Extension",
            "Amplification",
            "Internal Tandem Duplication",
            "Translocation",
            "Alleles",
            "Substitution",
            "Other",
            "Hypermethylation",
            "Duplication",
            "Fusion",
            "Mosaicism",
            "Gain",
            "Inversion",
            "Partial Methylation",
            "Deletion-Insertion",
            "Unknown",
            "Methylation",
            "Rearrangement",
            "Not Reported",
            "Splice",
            "Mutation, NOS",
            "Genetic Polymorphism",
        },
    )
    def variant_type(self, value):
        self._set_property("variant_type", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Unknown",
            "Not Reported",
            "Homozygous",
            "Hemizygous",
            "Heterozygous",
            "Nullizygous",
        },
    )
    def zygosity(self, value):
        self._set_property("zygosity", value)  # type: ignore  # inherited from CommonBase


datetime_hooks.cls_inject_created_datetime_hook(MolecularTest)
datetime_hooks.cls_inject_updated_datetime_hook(MolecularTest)
