from typing import Any, Dict, List, Optional, Tuple, Union

import psqlgraph
from sqlalchemy.ext import hybrid
from sqlalchemy.orm import Session, query

from .helpers import (
    base,
    datetime_hooks,
    indexes,
    related_cases,
    versioned_nodes,
    versioning,
)


class MolecularTest(base.Node):
    __tablename__: str = "node_moleculartest"

    # this field contains values of uniqueProperties
    __pg_secondary_keys: List[List[str]] = [["project_id", "submitter_id"]]

    # _defaults: default value for specified fields in the dictionary
    _defaults: Dict[str, Union[bool, float, int, str]] = {"state": "validated"}
    _dictionary: Dict[str, Union[bool, str, List[str]]] = {
        "title": "Molecular Test",
        "namespace": "https://gdc.cancer.gov",
        "category": "clinical",
        "submittable": True,
        "downloadable": False,
        "description": "Information pertaining to any molecular tests performed on the patient during a clinical event.",
        "required": [
            "submitter_id",
            "gene_symbol",
            "molecular_analysis_method",
            "test_result",
        ],
        "project": "*",
        "program": "*",
        "previous_version_downloadable": False,
    }

    _pg_backrefs: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_edges: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None
    _pg_links: Optional[Dict[str, Dict[str, Union[str, psqlgraph.Node]]]] = None

    @classmethod
    def get_label(cls) -> str:
        return "molecular_test"

    @property
    def id(self):
        return self.node_id

    @id.setter
    def id(self, value):
        self.node_id = value

    @classmethod
    def post_process(cls) -> None:
        cls.add_secondary_key_indexes()
        cls.populate_pg_backrefs()
        cls.populate_pg_links()
        cls.populate_pg_edges()

    @classmethod
    def add_secondary_key_indexes(cls) -> None:
        secondary_key_indexes = indexes.get_secondary_key_indexes(cls)
        for index in secondary_key_indexes:
            cls.__table__.append_constraint(index)

    @classmethod
    def populate_pg_backrefs(cls) -> None:
        """_pg_backrefs are in_edges, links FROM other types."""
        cls._pg_backrefs = {
            "annotations": {
                "name": "molecular_tests",
                "src_type": base.Node.get_subclass("annotation"),
            },
        }

    @classmethod
    def populate_pg_edges(cls) -> None:
        """_pg_edges are all edges, links to AND from other types."""
        cls._pg_edges = {
            "annotations": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("annotation"),
            },
            "diagnoses": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("diagnosis"),
            },
            "follow_ups": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("follow_up"),
            },
            "slides": {
                "backref": "molecular_tests",
                "type": base.Node.get_subclass("slide"),
            },
        }

    @classmethod
    def populate_pg_links(cls) -> None:
        """_pg_links are out_edges, links TO other types."""
        cls._pg_links = {
            "diagnoses": {
                "edge_out": "_MolecularTestRelatedToDiagnosis_out",
                "dst_type": base.Node.get_subclass("diagnosis"),
            },
            "follow_ups": {
                "edge_out": "_MolecularTestPerformedAtFollowUp_out",
                "dst_type": base.Node.get_subclass("follow_up"),
            },
            "slides": {
                "edge_out": "_MolecularTestRelatedToSlide_out",
                "dst_type": base.Node.get_subclass("slide"),
            },
        }

    @property
    def _related_cases_from_cache(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_cache(self)

    @property
    def _related_cases_from_parents(self) -> List[psqlgraph.Node]:
        return related_cases.get_related_cases_from_parents(self)

    @property
    def _secondary_keys_dicts(self) -> List[Dict[str, Any]]:
        vals = []
        secondary_keys = self.__pg_secondary_keys
        for keys in secondary_keys:
            if "id" in keys:
                continue
            vals.append({key: getattr(self, key, None) for key in keys})
        return vals

    @hybrid.hybrid_property
    def _secondary_keys(self) -> Tuple[Tuple[Any]]:
        vals = []
        for keys in self.__pg_secondary_keys:
            vals.append(tuple(getattr(self, key) for key in keys))
        return tuple(vals)

    @_secondary_keys.comparator
    def _secondary_keys(cls):
        return indexes.SecondaryKeyComparator(cls)

    # Set this attribute so psqlgraph doesn't treat it as a property
    _secondary_keys._is_pg_property = False

    @property
    def _versions(self) -> query.Query:
        """Return a query to get node versions (node history).

        Returns a query if the node is bound to a session. Raises an
            exception if the node is not bound to a session. This is different
            from node tagging and versioning. This is used by sheepdog to save
            node history when a node is updated. But the data seems never read by
            any repo.

        Args:
            self: Psqlgraph Node

        Returns:
            A SQLAlchemy query for node versions.

        Raises:
            RuntimeError if the node is not bound to a session.
        """
        session = self.get_session()
        if not session:
            raise RuntimeError(
                "{} not bound to a session. Try .get_versions(session).".format(self)
            )
        return self.get_versions(session)

    def get_versions(self, session: Session) -> query.Query:
        """Return a query for node versions given a session."""
        return (
            session.query(versioned_nodes.VersionedNode)
            .filter(versioned_nodes.VersionedNode.node_id == self.node_id)
            .filter(versioned_nodes.VersionedNode.label == self.label)
            .order_by(versioned_nodes.VersionedNode.key.desc())
        )

    @psqlgraph.pg_property(str)
    def submitter_id(self, value):
        self._set_property("submitter_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def batch_id(self, value):
        self._set_property("batch_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "validating",
            "suppressed",
            "live",
            "validated",
            "md5summing",
            "redacted",
            "invalid",
            "submitted",
            "uploading",
            "released",
            "error",
            "uploaded",
            "md5summed",
        },
    )
    def state(self, value):
        self._set_property("state", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def project_id(self, value):
        self._set_property("project_id", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(type(None), str)
    def created_datetime(self, value):
        self._set_property("created_datetime", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(type(None), str)
    def updated_datetime(self, value):
        self._set_property("updated_datetime", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def aa_change(self, value):
        self._set_property("aa_change", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "CD19",
            "CD10",
            "CD7",
            "CD14",
            "Lambda, Surface",
            "CD25",
            "CD33",
            "CD30",
            "CD138",
            "Kappa, Surface",
            "CD22",
            "CD56",
            "Prostate-Specific Antigen (PSA)",
            "Immunoglobulin, Cytoplasmic",
            "TAG-72",
            "BCL6",
            "Not Reported",
            "Immunoglobulin, Surface",
            "CD15",
            "CD117",
            "Squamous Cell Carcinoma Antigen (SCCA)",
            "NSE",
            "HLA-DR",
            "FMC-7",
            "CD23",
            "Unknown",
            "CA19-9",
            "CD5",
            "CD45",
            "CCND1",
            "CD34",
            "CD3",
            "Mesothelin",
            "CA-125",
            "CEA",
            "CD20",
            "CD79A",
            "Ki67",
        },
    )
    def antigen(self, value):
        self._set_property("antigen", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Monosomy", "Trisomy"})
    def aneuploidy(self, value):
        self._set_property("aneuploidy", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Buffy Coat",
            "Embryonic Tissue",
            "Uninvolved Tissue, NOS",
            "Involved Tissue, NOS",
            "Saliva",
            "Buccal Mucosa",
            "Blood",
            "Unknown",
            "Feces",
            "Pleural Fluid",
            "Peritoneal Fluid",
            "Urine",
            "Embryonic Fluid",
            "Nerve Tissue",
            "Serum",
            "Not Reported",
            "Skin",
            "Granulocyte",
            "Plasma",
            "Tissue, NOS",
            "Bone Marrow",
            "Cerebrospinal Fluid",
            "Connective Tissue",
            "Soft Tissue",
            "Muscle Tissue",
        },
    )
    def biospecimen_type(self, value):
        self._set_property("biospecimen_type", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def biospecimen_volume(self, value):
        self._set_property("biospecimen_volume", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def blood_test_normal_range_lower(self, value):
        self._set_property("blood_test_normal_range_lower", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def blood_test_normal_range_upper(self, value):
        self._set_property("blood_test_normal_range_upper", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def cell_count(self, value):
        self._set_property("cell_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "chr4",
            "chr8",
            "chrM",
            "chr12",
            "chr11",
            "chr9",
            "chr16",
            "chrX",
            "chr1",
            "chr20",
            "chr22",
            "chr15",
            "chr7",
            "chr14",
            "Unknown",
            "chr21",
            "chr23",
            "chr19",
            "chr5",
            "chr6",
            "chr10",
            "chr18",
            "Not Reported",
            "chr3",
            "chr13",
            "chr2",
            "chr17",
            "chrY",
        },
    )
    def chromosome(self, value):
        self._set_property("chromosome", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def copy_number(self, value):
        self._set_property("copy_number", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Non-clonal", "Clonal"})
    def clonality(self, value):
        self._set_property("clonality", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "t(6;9)",
            "Not Reported",
            "t(3;5)(q25;q34)",
            "t(9;11)(p22;q23)",
            "t(11;19)(q23;p13.1)",
            "t(8;21)",
            "t(6;11)(q27;q23)",
            "Unknown",
            "t(10;11)(p11.2;q23)",
        },
    )
    def chromosomal_translocation(self, value):
        self._set_property("chromosomal_translocation", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"p", "q", "Not Reported"})
    def chromosome_arm(self, value):
        self._set_property("chromosome_arm", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def cytoband(self, value):
        self._set_property("cytoband", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def days_to_test(self, value):
        self._set_property("days_to_test", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def exon(self, value):
        self._set_property("exon", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "HIF1A",
            "TAL1",
            "SDHB",
            "SGK1",
            "BCL3",
            "NTRK1",
            "IDH2",
            "STAG2",
            "ZNF521",
            "PRRX1",
            "JAZF1",
            "KEAP1",
            "FEV",
            "PATZ1",
            "KAT7",
            "FAS",
            "MYH9",
            "HOXC13",
            "CHD2",
            "LCK",
            "KDM5C",
            "CLP1",
            "DAXX",
            "HSP90AA1",
            "APC",
            "STRN",
            "XPC",
            "MTOR",
            "BRCA1",
            "KRAS",
            "IRF4",
            "ISX",
            "KMT2C",
            "HERPUD1",
            "PPP2R1A",
            "ARAF",
            "IRS4",
            "KLK2",
            "POLG",
            "FEN1",
            "LZTR1",
            "DUX4L1",
            "NBN",
            "PTPN13",
            "OMD",
            "TCF3",
            "ESR1",
            "FBLN2",
            "NOTCH2",
            "CARS",
            "CHCHD7",
            "TET2",
            "MALT1",
            "ROS1",
            "KLF4",
            "TSHR",
            "DDIT3",
            "MN1",
            "ITGAV",
            "JAK1",
            "BRIP1",
            "PTPN11",
            "VTI1A",
            "NCOR1",
            "SET",
            "PRKCB",
            "ETV6",
            "PPP6C",
            "NF2",
            "MUTYH",
            "STAT5B",
            "NTHL1",
            "PTPRT",
            "NRAS",
            "FH",
            "POLQ",
            "Unknown",
            "CD274",
            "PCBP1",
            "CHIC2",
            "TP53",
            "KDR",
            "USP6",
            "LRP1B",
            "CREB1",
            "ITK",
            "CALB2",
            "TOP1",
            "FLT4",
            "MYOD1",
            "HIP1",
            "RANBP2",
            "RGS7",
            "NCKIPSD",
            "BCL2",
            "MDM2",
            "FAM131B",
            "POU2AF1",
            "ZNF444",
            "CCNE1",
            "CBFA2T3",
            "EXT2",
            "PTEN",
            "TRAF7",
            "WWTR1",
            "CSMD3",
            "A1CF",
            "BMP5",
            "DGCR8",
            "KDM5A",
            "KCNJ5",
            "POLE",
            "CAMTA1",
            "RUNX1",
            "CBLC",
            "SETBP1",
            "U2AF1",
            "COL1A1",
            "MITF",
            "HMGA1",
            "TBL1XR1",
            "WT1",
            "MB21D2",
            "PAX7",
            "CCR7",
            "MAF",
            "DICER1",
            "CTNND2",
            "FHIT",
            "ACVR2A",
            "RMI2",
            "EPHA3",
            "SRSF3",
            "CLTC",
            "AXIN1",
            "NCOA4",
            "CDX2",
            "RNF43",
            "FIP1L1",
            "CHGA",
            "DDB2",
            "JAK2",
            "TRIM27",
            "TCL1A",
            "SNX29",
            "MSN",
            "SHTN1",
            "FOXO1",
            "BTG1",
            "TFG",
            "TPM4",
            "ZFHX3",
            "ACSL3",
            "PRKAR1A",
            "RABEP1",
            "HOXD11",
            "FLNA",
            "TBX3",
            "KNSTRN",
            "CCND3",
            "DROSHA",
            "BIRC6",
            "CDH17",
            "PGR",
            "TRA",
            "SUFU",
            "TSC1",
            "FBXO11",
            "FNBP1",
            "CCR4",
            "TCF7L2",
            "LYL1",
            "EIF1AX",
            "MUC16",
            "AKT3",
            "PDGFB",
            "CDH10",
            "GLI1",
            "NFKB2",
            "CIC",
            "TFEB",
            "CDC73",
            "HEY1",
            "EIF4A2",
            "REL",
            "ATF1",
            "ETV5",
            "SPEN",
            "MYD88",
            "TSC2",
            "FOXL2",
            "ATP1A1",
            "CTNNB1",
            "MYCL",
            "IKBKB",
            "MYC",
            "PTK6",
            "CNBD1",
            "NFE2L2",
            "ZEB1",
            "MAPK1",
            "THRAP3",
            "ZBTB16",
            "NBEA",
            "SFRP4",
            "LMNA",
            "FANCA",
            "ZRSR2",
            "VAV1",
            "KIF5B",
            "RBM15",
            "ALDH2",
            "ATIC",
            "MLLT11",
            "JUN",
            "CCNC",
            "HMGN2P46",
            "ZCCHC8",
            "CNBP",
            "S100A7",
            "XPO1",
            "MAFB",
            "TNFRSF17",
            "TRIP11",
            "NUP214",
            "ZNF331",
            "ZNF198",
            "TERT",
            "CD99",
            "TLX3",
            "SDC4",
            "SS18L1",
            "CDKN1A",
            "DEK",
            "RHOH",
            "BIRC3",
            "KIT",
            "BCL9",
            "FANCC",
            "ABL1",
            "HSP90AB1",
            "GNAQ",
            "FAM46C",
            "BCL6",
            "ARHGAP26",
            "GATA3",
            "PDGFRA",
            "ASXL2",
            "FOXR1",
            "ERC1",
            "MET",
            "MSH6",
            "CRLF2",
            "ERBB3",
            "MAML3",
            "PDPN",
            "ASPSCR1",
            "ETV4",
            "DDX3X",
            "TP63",
            "NACA",
            "CIITA",
            "ERBB4",
            "FLT3",
            "ACVR1",
            "BRD4",
            "PTPRB",
            "TGFBR2",
            "CYP2C8",
            "HOXB1",
            "WDCP",
            "AMER1",
            "BRAF",
            "CD79A",
            "FLCN",
            "CUL3",
            "SRC",
            "TRIM24",
            "LRIG3",
            "CD79B",
            "PALB2",
            "CDH11",
            "CSF1R",
            "MUC1",
            "SSX4",
            "CCDC6",
            "CLIP1",
            "NTRK3",
            "COL3A1",
            "H3F3B",
            "MYCN",
            "RALGDS",
            "BCL2L12",
            "MECOM",
            "FUS",
            "IL7R",
            "PBX1",
            "FANCF",
            "GOPC",
            "LEF1",
            "BCL11A",
            "SALL4",
            "SH2B3",
            "FANCD2",
            "FES",
            "ALK",
            "BCOR",
            "RAD51B",
            "SMAD4",
            "SMAD2",
            "STAT3",
            "RAP1GDS1",
            "FANCE",
            "CEP89",
            "ID3",
            "GPC3",
            "PML",
            "PMS1",
            "PHF6",
            "PABPC1",
            "KDM6A",
            "ARID1B",
            "ARHGAP5",
            "PIK3R1",
            "NSD1",
            "ZNF479",
            "UBR5",
            "GRM3",
            "ZNRF3",
            "SRGAP3",
            "PDGFRB",
            "FAM47C",
            "PWWP2A",
            "WRN",
            "YWHAE",
            "SDHA",
            "CARD11",
            "CACNA1D",
            "IL6ST",
            "FGFR4",
            "ARHGEF12",
            "BTK",
            "AKT2",
            "P2RY8",
            "LASP1",
            "SDHC",
            "PRDM1",
            "CCND2",
            "NUTM2B",
            "RPL22",
            "FAT1",
            "SYP",
            "LHFP",
            "BCORL1",
            "ZNF384",
            "DCAF12L2",
            "ATR",
            "PPFIBP1",
            "H3F3A",
            "SPOP",
            "MEN1",
            "STK11",
            "PIM1",
            "TRRAP",
            "CRTC3",
            "SOX2",
            "CHST11",
            "TAL2",
            "B2M",
            "PAX8",
            "CANT1",
            "DNTT",
            "ELF4",
            "PBRM1",
            "IGH",
            "SIRPA",
            "HOXA9",
            "TCF12",
            "KNL1",
            "AXIN2",
            "RPL5",
            "HOXA13",
            "IKZF1",
            "CHEK2",
            "POU5F1",
            "BRCA2",
            "SSX1",
            "TRB",
            "NOTCH1",
            "PTPRC",
            "GNAS",
            "ZNF429",
            "HOXA11",
            "ASXL1",
            "PPM1D",
            "IGL",
            "MIB1",
            "QKI",
            "C15orf65",
            "MKL1",
            "RSPO2",
            "DDX5",
            "MPL",
            "MALAT1",
            "MDS2",
            "FSTL3",
            "PIK3CA",
            "NFKBIE",
            "USP8",
            "ARID1A",
            "CNTRL",
            "FOXA1",
            "PTPRK",
            "ERCC4",
            "PCM1",
            "SKI",
            "CASP8",
            "SND1",
            "GATA1",
            "MED12",
            "NONO",
            "KDSR",
            "GOLGA5",
            "PRPF40B",
            "SDHAF2",
            "WAS",
            "KMT2A",
            "MAP2K1",
            "RUNX1T1",
            "FGFR1OP",
            "SMARCA4",
            "LSM14A",
            "CREB3L1",
            "CRTC1",
            "DNMT3A",
            "FGFR3",
            "BCL7A",
            "STAG1",
            "BARD1",
            "BCR",
            "KRT20",
            "SMO",
            "CDK4",
            "RPN1",
            "AR",
            "BAP1",
            "PTPN6",
            "ACKR3",
            "HNF1A",
            "ACSL6",
            "NCOR2",
            "SLC34A2",
            "FOXP1",
            "FUBP1",
            "GAS7",
            "MGMT",
            "HLA-A",
            "FANCG",
            "KMT2D",
            "SMARCD1",
            "TEC",
            "PREX2",
            "ELK4",
            "MLH1",
            "NUTM1",
            "NUTM2A",
            "BCLAF1",
            "NR4A3",
            "ETNK1",
            "TFRC",
            "ATP2B3",
            "Not Applicable",
            "CLTCL1",
            "NAB2",
            "RB1",
            "TFE3",
            "NT5C2",
            "HOXD13",
            "TMEM127",
            "BUB1B",
            "SBDS",
            "CDH1",
            "SFPQ",
            "NFATC2",
            "EGFR",
            "SF3B1",
            "MLH2",
            "SMARCE1",
            "CDK12",
            "DCTN1",
            "HOXC11",
            "PLCG1",
            "MLLT10",
            "GNA11",
            "MAP3K1",
            "CTNND1",
            "MDM4",
            "IDH1",
            "MYO5A",
            "NDRG1",
            "PRF1",
            "PRDM16",
            "SEPT9",
            "TMPRSS2",
            "KAT6A",
            "SETD2",
            "NFIB",
            "EPAS1",
            "POT1",
            "RPL10",
            "KIAA1549",
            "KRT7",
            "LMO2",
            "TLR2",
            "AQP1",
            "Not Reported",
            "NSD3",
            "SSX2",
            "STIL",
            "ATRX",
            "NSD2",
            "MLLT1",
            "KAT6B",
            "BRD3",
            "RARA",
            "FCRL4",
            "CXCR4",
            "TAF15",
            "AKT1",
            "ELN",
            "HMGA2",
            "HNRNPA2B1",
            "CHD4",
            "OLIG2",
            "FOXO3",
            "EXT1",
            "FAT3",
            "IGKC",
            "MNX1",
            "BCL11B",
            "PHOX2B",
            "FLI1",
            "RAD21",
            "HOOK3",
            "PDE4DIP",
            "PICALM",
            "TPM3",
            "DCC",
            "MSH2",
            "WIF1",
            "CBL",
            "SUZ12",
            "DNM2",
            "CD28",
            "PTGS2",
            "ELF3",
            "CCNB1IP1",
            "EML4",
            "PRKACA",
            "EED",
            "TLX1",
            "IGK",
            "APOBEC3B",
            "KTN1",
            "FGFR2",
            "TFPT",
            "NCOA2",
            "IL2",
            "BCL9L",
            "EPCAM",
            "EPS15",
            "SMARCB1",
            "SDHD",
            "SMAD3",
            "CDK6",
            "MLLT4",
            "NIN",
            "RNF213",
            "NCOA1",
            "FOXO4",
            "BMPR1A",
            "SLC45A3",
            "ARNT",
            "MLF1",
            "POLD1",
            "MAP3K13",
            "MAML2",
            "GMPS",
            "RECQL4",
            "GATA2",
            "TNC",
            "MLLT6",
            "HRAS",
            "ANK1",
            "TPR",
            "PPARG",
            "CALR",
            "CREBBP",
            "WNK2",
            "EZH2",
            "CBLB",
            "GRIN2A",
            "XPA",
            "CSF3R",
            "EP300",
            "AFF3",
            "MYH11",
            "NUMA1",
            "LARP4B",
            "PMS2",
            "TNFRSF14",
            "CNTNAP2",
            "CUX1",
            "CNOT3",
            "ECT2L",
            "FAT4",
            "RHOA",
            "CD74",
            "JAK3",
            "EZR",
            "PLAG1",
            "LMO1",
            "DNAJB1",
            "CDKN2C",
            "TCEA1",
            "ETV1",
            "CYSLTR2",
            "FCGR2B",
            "CYLD",
            "SYK",
            "MSI2",
            "MUC4",
            "IL21R",
            "ABI1",
            "CCND1",
            "FGFR1",
            "EPHA7",
            "EIF3E",
            "ELL",
            "MAX",
            "MTCP1",
            "ROBO2",
            "NF1",
            "ATM",
            "SEPT5",
            "TRIM33",
            "BCL10",
            "EWSR1",
            "SPECC1",
            "MAP2K2",
            "TRD",
            "STAT6",
            "GPHN",
            "MAP2K4",
            "NPM1",
            "EBF1",
            "LCP1",
            "CD209",
            "CBFB",
            "ABL2",
            "CTCF",
            "NUP98",
            "SMC1A",
            "TNFAIP3",
            "SEPT6",
            "CTNNA2",
            "NKX2-1",
            "MLLT3",
            "NRG1",
            "PDCD1LG2",
            "CEBPA",
            "VHL",
            "DDR2",
            "PER1",
            "PIK3CB",
            "LIFR",
            "PTCH1",
            "PRCC",
            "CDKN2A",
            "HLF",
            "FBXW7",
            "KLF6",
            "RGPD3",
            "RBM10",
            "GCET1",
            "RAF1",
            "PSIP1",
            "LPP",
            "DDX10",
            "HIST1H3B",
            "PAX3",
            "SRSF2",
            "CRNKL1",
            "ERG",
            "CREB3L2",
            "AFF4",
            "PRDM2",
            "ERCC5",
            "DDX6",
            "AFF1",
            "COX6C",
            "COL2A1",
            "ARID2",
            "RET",
            "MYB",
            "FKBP9",
            "PAX5",
            "RAC1",
            "HIST1H4I",
            "BLM",
            "AKAP9",
            "FAM135B",
            "ZMYM3",
            "ERCC3",
            "RSPO3",
            "ERCC2",
            "TET1",
            "PAFAH1B2",
            "SH3GL1",
            "SS18",
            "CDKN1B",
            "ERBB2",
            "SOCS1",
        },
    )
    def gene_symbol(self, value):
        self._set_property("gene_symbol", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"H1", "Unknown", "H3", "H2A", "Not Reported", "H2B", "H4"})
    def histone_family(self, value):
        self._set_property("histone_family", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "H3.1",
            "mH2A.1",
            "H2A.Z.2",
            "H2A.Z.1",
            "CENP-A",
            "Unknown",
            "H3.X",
            "mH2A.2",
            "H2A.Z.2.2",
            "H2A.X",
            "H3.3",
            "H3.Y",
            "mH2A",
            "Not Reported",
            "H3t (H3.4)",
            "H2A.Z",
            "H3.5",
            "H3.2",
            "H2A-Bbd",
        },
    )
    def histone_variant(self, value):
        self._set_property("histone_variant", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "HPV35",
            "HPV59",
            "HPV56",
            "HPV58",
            "HPV51",
            "HPV52",
            "HPV66",
            "HPV16",
            "HPV73",
            "HPV31",
            "HPV68",
            "HPV18",
            "HPV33",
            "HPV39",
            "HPV45",
        },
    )
    def hpv_strain(self, value):
        self._set_property("hpv_strain", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def intron(self, value):
        self._set_property("intron", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Glucose",
            "HPV-E6/E7",
            "Neutrophil Bands",
            "Methoxytyramine-Secreting",
            "Eosinophil",
            "C-Reactive Protein",
            "Norepinephrine-Secreting",
            "Human Papillomavirus",
            "B-cell genotyping",
            "Testosterone",
            "Segmented Neutrophil",
            "Immunoglobulin M",
            "Cytokeratin 5",
            "Myelocytes",
            "Dopamine-Secreting",
            "Immunoglobulin G",
            "Metaphase Nucleus Count",
            "Promyelocytes",
            "Cellularity",
            "Absolute Neutrophil",
            "Immunoglobulin A",
            "5-Hydroxyindoleacetic Acid",
            "Normetanephrine-Secreting",
            "Prothrombin Time",
            "Luteinizing Hormone",
            "Gamma-Enolase",
            "Platelets",
            "Metanephrine-Secreting",
            "Hemoglobin",
            "Human Chorionic Gonadotropin",
            "Creatinine",
            "Calcium",
            "Leukocytes",
            "Chromogranin B",
            "Serum Free Immunoglobulin Light Chain, Kappa",
            "Circulating Endothelial Cells",
            "Lymphocytes",
            "Erythrocyte Sedimentation Rate",
            "BG8",
            "Epstein-Barr Virus",
            "Myeloblasts",
            "Microsatellite Instability",
            "Hematocrit",
            "Metamyelocytes",
            "Serum Free Immunoglobulin Light Chain, Lambda",
            "Promonocytes",
            "Basophil",
            "TAG-72",
            "Epinephrine-Secreting",
            "M Protein",
            "Minimal Residual Disease",
            "Not Reported",
            "Serum Free Immunoglobulin Light Chain, NOS",
            "Beta 2 Microglobulin",
            "Total Bilirubin",
            "Albumin",
            "Prolymphocytes",
            "Cytokeratin 6",
            "Unknown",
            "Circulating Tumor Cells",
            "Chromogranin A",
            "Alpha Fetoprotein",
            "Lactate Dehydrogenase",
            "Blast Count",
            "Total Protein",
            "Lymphoblasts",
            "Blood Urea Nitrogen",
            "Monocytes",
            "Serum Mesothelin",
        },
    )
    def laboratory_test(self, value):
        self._set_property("laboratory_test", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def loci_abnormal_count(self, value):
        self._set_property("loci_abnormal_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(int)
    def loci_count(self, value):
        self._set_property("loci_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def locus(self, value):
        self._set_property("locus", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Unknown", "Not Reported", "Yes", "No"})
    def mismatch_repair_mutation(self, value):
        self._set_property("mismatch_repair_mutation", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def mitotic_count(self, value):
        self._set_property("mitotic_count", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def mitotic_total_area(self, value):
        self._set_property("mitotic_total_area", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Southern Blotting",
            "Microsatellite Analysis",
            "Immunofluorescence",
            "Other",
            "ISH",
            "Flow Cytometry",
            "WGS",
            "FISH",
            "IHC",
            "Unknown",
            "Cytogenetics, NOS",
            "RT-PCR",
            "Nuclear Staining",
            "RNA Sequencing",
            "Karyotype",
            "Not Reported",
            "Comparative Genomic Hybridization",
            "Sequencing, NOS",
            "Microarray",
            "PCR",
            "Targeted Sequencing",
            "WXS",
        },
    )
    def molecular_analysis_method(self, value):
        self._set_property("molecular_analysis_method", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Missense Variant",
            "Feature Truncation",
            "Downstream Gene Variant",
            "Frameshift Variant",
            "Splice Acceptor Variant",
            "Non-coding Transcript Exon Variant",
            "Stop Retained Variant",
            "Non-coding Transcript Variant",
            "Intergenic Variant",
            "Splice Region Variant",
            "Upstream Gene Variant",
            "Coding Sequence Variant",
            "3 Prime UTR Variant",
            "Inframe Deletion",
            "Transcript Ablation",
            "TFBS Amplification",
            "Regulatory Region Amplification",
            "Start Lost",
            "Mature miRNA Variant",
            "Incomplete Terminal Codon Variant",
            "TF Binding Site Variant",
            "Transcript Amplification",
            "Stop Lost",
            "Inframe Insertion",
            "Intron Variant",
            "Regulatory Region Ablation",
            "Nonsense",
            "Protein Altering Variant",
            "Synonymous Variant",
            "TFBS Ablation",
            "Exon Variant",
            "Regulatory Region Variant",
            "Feature Elongation",
            "Splice Donor Variant",
            "NMD Transcript Variant",
            "Stop Gain",
            "5 Prime UTR Variant",
        },
    )
    def molecular_consequence(self, value):
        self._set_property("molecular_consequence", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"61", "13", "12"})
    def mutation_codon(self, value):
        self._set_property("mutation_codon", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Uncertain Significance",
            "Benign",
            "Likely Benign",
            "Likely Pathogenic",
            "Pathogenic",
        },
    )
    def pathogenicity(self, value):
        self._set_property("pathogenicity", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Diploid",
            "Aneuploid",
            "Not Reported",
            "Tetraploid",
            "Near Diploid",
            "Hypodiploid",
            "Unknown",
            "Hyperdiploid",
        },
    )
    def ploidy(self, value):
        self._set_property("ploidy", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def second_exon(self, value):
        self._set_property("second_exon", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "HIF1A",
            "TAL1",
            "SDHB",
            "SGK1",
            "BCL3",
            "NTRK1",
            "IDH2",
            "STAG2",
            "ZNF521",
            "PRRX1",
            "JAZF1",
            "KEAP1",
            "FEV",
            "PATZ1",
            "KAT7",
            "FAS",
            "MYH9",
            "HOXC13",
            "CHD2",
            "LCK",
            "KDM5C",
            "CLP1",
            "DAXX",
            "HSP90AA1",
            "APC",
            "STRN",
            "XPC",
            "MTOR",
            "BRCA1",
            "KRAS",
            "IRF4",
            "ISX",
            "KMT2C",
            "HERPUD1",
            "PPP2R1A",
            "ARAF",
            "IRS4",
            "KLK2",
            "POLG",
            "FEN1",
            "LZTR1",
            "DUX4L1",
            "NBN",
            "PTPN13",
            "OMD",
            "TCF3",
            "ESR1",
            "FBLN2",
            "NOTCH2",
            "CARS",
            "CHCHD7",
            "TET2",
            "MALT1",
            "ROS1",
            "KLF4",
            "TSHR",
            "DDIT3",
            "MN1",
            "ITGAV",
            "JAK1",
            "BRIP1",
            "PTPN11",
            "VTI1A",
            "NCOR1",
            "SET",
            "PRKCB",
            "ETV6",
            "PPP6C",
            "NF2",
            "MUTYH",
            "STAT5B",
            "NTHL1",
            "PTPRT",
            "NRAS",
            "FH",
            "POLQ",
            "Unknown",
            "CD274",
            "PCBP1",
            "CHIC2",
            "TP53",
            "KDR",
            "USP6",
            "LRP1B",
            "CREB1",
            "ITK",
            "TOP1",
            "FLT4",
            "MYOD1",
            "HIP1",
            "RANBP2",
            "RGS7",
            "NCKIPSD",
            "BCL2",
            "MDM2",
            "FAM131B",
            "POU2AF1",
            "ZNF444",
            "CCNE1",
            "CBFA2T3",
            "EXT2",
            "PTEN",
            "TRAF7",
            "WWTR1",
            "CSMD3",
            "A1CF",
            "BMP5",
            "DGCR8",
            "KDM5A",
            "KCNJ5",
            "POLE",
            "CAMTA1",
            "RUNX1",
            "CBLC",
            "SETBP1",
            "U2AF1",
            "COL1A1",
            "MITF",
            "HMGA1",
            "TBL1XR1",
            "WT1",
            "MB21D2",
            "PAX7",
            "CCR7",
            "MAF",
            "DICER1",
            "CTNND2",
            "FHIT",
            "ACVR2A",
            "RMI2",
            "EPHA3",
            "SRSF3",
            "CLTC",
            "AXIN1",
            "NCOA4",
            "CDX2",
            "RNF43",
            "FIP1L1",
            "CHGA",
            "DDB2",
            "JAK2",
            "TRIM27",
            "TCL1A",
            "SNX29",
            "MSN",
            "SHTN1",
            "FOXO1",
            "BTG1",
            "TFG",
            "TPM4",
            "ZFHX3",
            "ACSL3",
            "PRKAR1A",
            "RABEP1",
            "HOXD11",
            "FLNA",
            "TBX3",
            "KNSTRN",
            "CCND3",
            "DROSHA",
            "BIRC6",
            "CDH17",
            "PGR",
            "TRA",
            "SUFU",
            "TSC1",
            "FBXO11",
            "FNBP1",
            "CCR4",
            "TCF7L2",
            "LYL1",
            "EIF1AX",
            "MUC16",
            "AKT3",
            "PDGFB",
            "CDH10",
            "GLI1",
            "NFKB2",
            "CIC",
            "TFEB",
            "CDC73",
            "HEY1",
            "EIF4A2",
            "REL",
            "ATF1",
            "ETV5",
            "SPEN",
            "MYD88",
            "TSC2",
            "FOXL2",
            "ATP1A1",
            "CTNNB1",
            "MYCL",
            "IKBKB",
            "MYC",
            "PTK6",
            "CNBD1",
            "NFE2L2",
            "ZEB1",
            "MAPK1",
            "THRAP3",
            "ZBTB16",
            "NBEA",
            "SFRP4",
            "LMNA",
            "FANCA",
            "ZRSR2",
            "VAV1",
            "KIF5B",
            "RBM15",
            "ALDH2",
            "ATIC",
            "MLLT11",
            "JUN",
            "CCNC",
            "HMGN2P46",
            "ZCCHC8",
            "CNBP",
            "S100A7",
            "XPO1",
            "MAFB",
            "TNFRSF17",
            "TRIP11",
            "NUP214",
            "ZNF331",
            "ZNF198",
            "TERT",
            "CD99",
            "TLX3",
            "SDC4",
            "SS18L1",
            "CDKN1A",
            "DEK",
            "RHOH",
            "BIRC3",
            "KIT",
            "BCL9",
            "FANCC",
            "ABL1",
            "HSP90AB1",
            "GNAQ",
            "FAM46C",
            "BCL6",
            "ARHGAP26",
            "GATA3",
            "PDGFRA",
            "ASXL2",
            "FOXR1",
            "ERC1",
            "MET",
            "MSH6",
            "CRLF2",
            "ERBB3",
            "MAML3",
            "ASPSCR1",
            "ETV4",
            "DDX3X",
            "TP63",
            "NACA",
            "CIITA",
            "ERBB4",
            "FLT3",
            "ACVR1",
            "BRD4",
            "PTPRB",
            "TGFBR2",
            "CYP2C8",
            "HOXB1",
            "WDCP",
            "AMER1",
            "BRAF",
            "CD79A",
            "FLCN",
            "CUL3",
            "SRC",
            "TRIM24",
            "LRIG3",
            "CD79B",
            "PALB2",
            "CDH11",
            "CSF1R",
            "MUC1",
            "SSX4",
            "CCDC6",
            "CLIP1",
            "NTRK3",
            "COL3A1",
            "H3F3B",
            "MYCN",
            "RALGDS",
            "BCL2L12",
            "MECOM",
            "FUS",
            "IL7R",
            "PBX1",
            "FANCF",
            "GOPC",
            "LEF1",
            "BCL11A",
            "SALL4",
            "SH2B3",
            "FANCD2",
            "FES",
            "ALK",
            "BCOR",
            "RAD51B",
            "SMAD4",
            "SMAD2",
            "STAT3",
            "RAP1GDS1",
            "FANCE",
            "CEP89",
            "ID3",
            "GPC3",
            "PML",
            "PMS1",
            "PHF6",
            "PABPC1",
            "KDM6A",
            "ARID1B",
            "ARHGAP5",
            "PIK3R1",
            "NSD1",
            "ZNF479",
            "UBR5",
            "GRM3",
            "ZNRF3",
            "SRGAP3",
            "PDGFRB",
            "FAM47C",
            "PWWP2A",
            "WRN",
            "YWHAE",
            "SDHA",
            "CARD11",
            "CACNA1D",
            "IL6ST",
            "FGFR4",
            "ARHGEF12",
            "BTK",
            "AKT2",
            "P2RY8",
            "LASP1",
            "SDHC",
            "PRDM1",
            "CCND2",
            "NUTM2B",
            "RPL22",
            "FAT1",
            "SYP",
            "LHFP",
            "BCORL1",
            "ZNF384",
            "DCAF12L2",
            "ATR",
            "PPFIBP1",
            "H3F3A",
            "SPOP",
            "MEN1",
            "STK11",
            "PIM1",
            "TRRAP",
            "CRTC3",
            "SOX2",
            "CHST11",
            "TAL2",
            "B2M",
            "PAX8",
            "CANT1",
            "ELF4",
            "PBRM1",
            "IGH",
            "SIRPA",
            "HOXA9",
            "TCF12",
            "KNL1",
            "AXIN2",
            "RPL5",
            "HOXA13",
            "IKZF1",
            "CHEK2",
            "POU5F1",
            "BRCA2",
            "SSX1",
            "TRB",
            "NOTCH1",
            "PTPRC",
            "GNAS",
            "ZNF429",
            "HOXA11",
            "ASXL1",
            "PPM1D",
            "IGL",
            "QKI",
            "C15orf65",
            "MKL1",
            "RSPO2",
            "DDX5",
            "MPL",
            "MALAT1",
            "MDS2",
            "FSTL3",
            "PIK3CA",
            "NFKBIE",
            "USP8",
            "ARID1A",
            "CNTRL",
            "FOXA1",
            "PTPRK",
            "ERCC4",
            "PCM1",
            "SKI",
            "CASP8",
            "SND1",
            "GATA1",
            "MED12",
            "NONO",
            "KDSR",
            "GOLGA5",
            "PRPF40B",
            "SDHAF2",
            "WAS",
            "KMT2A",
            "MAP2K1",
            "RUNX1T1",
            "FGFR1OP",
            "SMARCA4",
            "LSM14A",
            "CREB3L1",
            "CRTC1",
            "DNMT3A",
            "FGFR3",
            "BCL7A",
            "STAG1",
            "BARD1",
            "BCR",
            "SMO",
            "CDK4",
            "RPN1",
            "AR",
            "BAP1",
            "PTPN6",
            "ACKR3",
            "HNF1A",
            "ACSL6",
            "NCOR2",
            "SLC34A2",
            "FOXP1",
            "FUBP1",
            "GAS7",
            "MGMT",
            "HLA-A",
            "FANCG",
            "KMT2D",
            "SMARCD1",
            "TEC",
            "PREX2",
            "ELK4",
            "MLH1",
            "NUTM1",
            "NUTM2A",
            "BCLAF1",
            "NR4A3",
            "ETNK1",
            "TFRC",
            "ATP2B3",
            "CLTCL1",
            "NAB2",
            "RB1",
            "TFE3",
            "NT5C2",
            "HOXD13",
            "TMEM127",
            "BUB1B",
            "SBDS",
            "CDH1",
            "SFPQ",
            "NFATC2",
            "EGFR",
            "SF3B1",
            "MLH2",
            "SMARCE1",
            "CDK12",
            "DCTN1",
            "HOXC11",
            "PLCG1",
            "MLLT10",
            "GNA11",
            "MAP3K1",
            "CTNND1",
            "MDM4",
            "IDH1",
            "MYO5A",
            "NDRG1",
            "PRF1",
            "PRDM16",
            "SEPT9",
            "TMPRSS2",
            "KAT6A",
            "SETD2",
            "NFIB",
            "EPAS1",
            "POT1",
            "RPL10",
            "KIAA1549",
            "LMO2",
            "TLR2",
            "Not Reported",
            "NSD3",
            "SSX2",
            "STIL",
            "ATRX",
            "NSD2",
            "MLLT1",
            "KAT6B",
            "BRD3",
            "RARA",
            "FCRL4",
            "CXCR4",
            "TAF15",
            "AKT1",
            "ELN",
            "HMGA2",
            "HNRNPA2B1",
            "CHD4",
            "OLIG2",
            "FOXO3",
            "EXT1",
            "FAT3",
            "MNX1",
            "BCL11B",
            "PHOX2B",
            "FLI1",
            "RAD21",
            "HOOK3",
            "PDE4DIP",
            "PICALM",
            "TPM3",
            "DCC",
            "MSH2",
            "WIF1",
            "CBL",
            "SUZ12",
            "DNM2",
            "CD28",
            "ELF3",
            "CCNB1IP1",
            "EML4",
            "PRKACA",
            "EED",
            "TLX1",
            "IGK",
            "APOBEC3B",
            "KTN1",
            "FGFR2",
            "TFPT",
            "NCOA2",
            "IL2",
            "BCL9L",
            "EPS15",
            "SMARCB1",
            "SDHD",
            "SMAD3",
            "CDK6",
            "MLLT4",
            "NIN",
            "RNF213",
            "NCOA1",
            "FOXO4",
            "BMPR1A",
            "SLC45A3",
            "ARNT",
            "MLF1",
            "POLD1",
            "MAP3K13",
            "MAML2",
            "GMPS",
            "RECQL4",
            "GATA2",
            "TNC",
            "MLLT6",
            "HRAS",
            "ANK1",
            "TPR",
            "PPARG",
            "CALR",
            "CREBBP",
            "WNK2",
            "EZH2",
            "CBLB",
            "GRIN2A",
            "XPA",
            "CSF3R",
            "EP300",
            "AFF3",
            "MYH11",
            "NUMA1",
            "LARP4B",
            "PMS2",
            "TNFRSF14",
            "CNTNAP2",
            "CUX1",
            "CNOT3",
            "ECT2L",
            "FAT4",
            "RHOA",
            "CD74",
            "JAK3",
            "EZR",
            "PLAG1",
            "LMO1",
            "DNAJB1",
            "CDKN2C",
            "TCEA1",
            "ETV1",
            "CYSLTR2",
            "FCGR2B",
            "CYLD",
            "SYK",
            "MSI2",
            "MUC4",
            "IL21R",
            "ABI1",
            "CCND1",
            "FGFR1",
            "EPHA7",
            "EIF3E",
            "ELL",
            "MAX",
            "MTCP1",
            "ROBO2",
            "NF1",
            "ATM",
            "SEPT5",
            "TRIM33",
            "BCL10",
            "EWSR1",
            "SPECC1",
            "MAP2K2",
            "TRD",
            "STAT6",
            "GPHN",
            "MAP2K4",
            "NPM1",
            "EBF1",
            "LCP1",
            "CD209",
            "CBFB",
            "ABL2",
            "CTCF",
            "NUP98",
            "SMC1A",
            "TNFAIP3",
            "SEPT6",
            "CTNNA2",
            "NKX2-1",
            "MLLT3",
            "NRG1",
            "PDCD1LG2",
            "CEBPA",
            "VHL",
            "DDR2",
            "PER1",
            "PIK3CB",
            "LIFR",
            "PTCH1",
            "PRCC",
            "CDKN2A",
            "HLF",
            "FBXW7",
            "KLF6",
            "RGPD3",
            "RBM10",
            "RAF1",
            "PSIP1",
            "LPP",
            "DDX10",
            "HIST1H3B",
            "PAX3",
            "SRSF2",
            "CRNKL1",
            "ERG",
            "CREB3L2",
            "AFF4",
            "PRDM2",
            "ERCC5",
            "DDX6",
            "AFF1",
            "COX6C",
            "COL2A1",
            "ARID2",
            "RET",
            "MYB",
            "FKBP9",
            "PAX5",
            "RAC1",
            "HIST1H4I",
            "BLM",
            "AKAP9",
            "FAM135B",
            "ZMYM3",
            "ERCC3",
            "RSPO3",
            "ERCC2",
            "TET1",
            "PAFAH1B2",
            "SH3GL1",
            "SS18",
            "CDKN1B",
            "ERBB2",
            "SOCS1",
        },
    )
    def second_gene_symbol(self, value):
        self._set_property("second_gene_symbol", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def specialized_molecular_test(self, value):
        self._set_property("specialized_molecular_test", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Total RNA",
            "Protein",
            "mRNA",
            "Unknown",
            "miRNA",
            "Not Reported",
            "DNA",
        },
    )
    def test_analyte_type(self, value):
        self._set_property("test_analyte_type", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Elevated",
            "Positive",
            "Low",
            "Copy Number Reported",
            "Equivocal",
            "Intermediate",
            "Unknown",
            "Normal",
            "Stable",
            "Overexpressed",
            "Amplified",
            "Loss of Expression",
            "Abnormal, NOS",
            "Not Reported",
            "Test Value Reported",
            "Not Amplified",
            "High",
            "Negative",
        },
    )
    def test_result(self, value):
        self._set_property("test_result", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "mg/dL",
            "mmol/L",
            "U/mL",
            "x10^3 cells/mcL",
            "count x10^9/L",
            "ng/mL",
            "mU/mol Hb",
            "U/g Hb",
            "ukat/L",
            "Unknown",
            "mg/L",
            "g/dL",
            "mg/24 hr",
            "mcg/L",
            "mcg/mL",
            "Not Reported",
            "mm^2",
            "percent",
            "U/L",
            "umol/L",
            "g/L",
            "cells/mL",
            "x10^9 cells/L",
        },
    )
    def test_units(self, value):
        self._set_property("test_units", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(float, int)
    def test_value(self, value):
        self._set_property("test_value", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"0-25", "26-50", "76-100", "51-75", "Not Reported"})
    def test_value_range(self, value):
        self._set_property("test_value_range", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "End of Treatment Course 1",
            "Not Reported",
            "End of Consolidation Therapy",
            "End of Treatment Course 2",
        },
    )
    def timepoint_category(self, value):
        self._set_property("timepoint_category", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str)
    def transcript(self, value):
        self._set_property("transcript", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(str, enum={"Germline", "Somatic", "Unknown"})
    def variant_origin(self, value):
        self._set_property("variant_origin", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Inversion",
            "Insertion",
            "Gain",
            "Fusion",
            "Other",
            "Hypermethylation",
            "Internal Tandem Duplication",
            "Chrimerism",
            "Unknown",
            "Conversion",
            "Splice",
            "Methylation",
            "Loss",
            "Translocation",
            "Deletion-Insertion",
            "Repeated Sequences",
            "Deletion",
            "Genetic Polymorphism",
            "Amplification",
            "Alleles",
            "Mosaicism",
            "Mutation, NOS",
            "Not Reported",
            "Extension",
            "Partial Methylation",
            "Substitution",
            "Rearrangement",
            "Duplication",
        },
    )
    def variant_type(self, value):
        self._set_property("variant_type", value)  # type: ignore  # inherited from CommonBase

    @psqlgraph.pg_property(
        str,
        enum={
            "Nullizygous",
            "Heterozygous",
            "Hemizygous",
            "Unknown",
            "Not Reported",
            "Homozygous",
        },
    )
    def zygosity(self, value):
        self._set_property("zygosity", value)  # type: ignore  # inherited from CommonBase


datetime_hooks.cls_inject_created_datetime_hook(MolecularTest)
datetime_hooks.cls_inject_updated_datetime_hook(MolecularTest)
